### ISSUE TITLE
Event Logs

### ISSUE THREAD

**Issue by zafarali** [CompuCell3D/CompuCell3D#10]
Hi!

I was wondering if CompuCell3D has a built in way of storing events (mitosis, division, growth) etc.
Are there any plugins which allow us to do this?

Also was wondering which genome expression network you recommend to use with CC3D?

Thanks

**Comment by maciekswat** [comment]
I was wondering if CompuCell3D has a built in way of storing events (mitosis, division, growth) etc.
Are there any plugins which allow us to do this?

We do not provide automatic logging capability but you can easily implement it yourself. See for example our demo located in Demos/Models/cellsort/cellsort_2D_growing_cells_mitosis_using_steppable 

It will give you an idea of what to do and how

Also was wondering which genome expression network you recommend to use with CC3D?

This is huge question. It really depends what you want to model.

**Comment by zafarali** [comment]
Thanks for the response!

In regards for the genome expression network, what are some of the existing solutions. Maybe if you give me a few names I'd be able to get a better idea of what I need!

Thank you
