### ISSUE TITLE
Wrong windows download link

### ISSUE THREAD

**Issue by Pablo1990** [CompuCell3D/CompuCell3D#105]
In http://www.compucell3d.org/SrcBin the download link of windows exe is wrong:
http://www.compucell3d.org/rceforge.net/projects/cc3d/files/rc-3.7.8/windows/

I think it should be :
http://www.sourceforge.net/projects/cc3d/files/rc-3.7.8/windows/

Best wishes,
Pablo

**Comment by CompuCell3D** [comment]
Fixed. Thank you!
