### ISSUE TITLE
Preferences Not Saving

### ISSUE THREAD

**Issue by zcapcso** [CompuCell3D/CompuCell3D#113]
I have attempted to change features such as: the color of cells, the frequency of saving images, the border axes etc in the Preferences window of Compucell3d, but when I start another simulation (after pressing 'Apply' and 'OK'), the features revert to their old settings as if I never made the changes. A new window does open whenever a new simulation begins, but this shouldn't make a difference, should it?
It'll be difficult for me to work with simulation output data given the current settings, so I'd appreciate any possible help on this front!
(I'm using CC3D Version 3.7.8 on Mac OS X).

**Comment by jpsluka** [comment]
Compucell3D stores the player’s settings in a file called _settings.sqlite, which is located in your job’s “Simulation” folder. When you change a setting in Player that data is supposed to be immediately written to the _settings.sqlite file. When Player is started and you load a CC3D job that file should be read and the Player should setup as it was before.

 

If this isn’t working I would check the following;

1.	Try updating to the latest CC3D version 3.7.9 (http://www.compucell3d.org/SrcBin)
2.	Check the time stamp on the _settings.sqlite file. Is it getting updated when you make a change in player (like changing cell colors)?
3.	Do you have write authority in the Simulation folder?

 

When you run a new job with a new job name and new job and simulation folders you’ll need to copy the _settings.sqlite file to the new folder.

 

The _settings.sqlite is binary and can‘t easily be checked or modified. There is an online viewer at http://inloop.github.io/sqlite-viewer/ that will show you what is in the file. There are also free tools to edit the file such as https://sqlitebrowser.org/, though we don’t recommend actually editing the file manually.

 

Let me know if any of the above work or if you are still having problems.

 

Jim

 

James P. Sluka, PhD
Biocomplexity Institute

Intelligent Systems Engineering

School of Informatics, Computing and Engineering

Indiana University

Bloomington, IN   USA

Office: 812-855-2441

Cell: 317-331-7465

 <mailto:JSluka@Indiana.edu> JSluka@Indiana.edu

**Comment by CompuCell3D** [comment]
Closing the issue
