### ISSUE TITLE
vtk module not found although older version finds it

### ISSUE THREAD

**Issue by lemaiw** [CompuCell3D/CompuCell3D#115]
I've compiled compucell3d version 3.7.5 before and it installed successfully. I am now trying to install the newest version (3.7.9) and am using the same python and vtk versions used to compile 3.7.5. Everything builds without errors and compucell3d/3.7.9 is installed. However, upon trying to run runScript.sh with the new version, complaints are made that the vtk module cannot be found albeit a simple python -c "import vtk;" results in no errors. 

```
[llnguyen@h2 ~]$ bash runScript.sh -i /N/soft/rhel6/compucell3d/3.7.9/Demos/Models/cellsort/cellsort_2D/cellsort_2D.cc3d
/N/soft/rhel6/compucell3d/3.7.9/runScript.sh: line 6: warning: setlocale: LC_NUMERIC: cannot change locale (C.UTF-8): No such file or directory
/N/soft/rhel6/compucell3d/3.7.9/runScript.sh: line 6: warning: setlocale: LC_NUMERIC: cannot change locale (C.UTF-8)
CompuCell3D - version 3.7.9
Traceback (most recent call last):
  File "/N/soft/rhel6/compucell3d/3.7.9/player5/CompuCellPythonSimulationCML.py", line 203, in <module>
    import vtk
ImportError: No module named vtk
[llnguyen@h2 ~]$ python -c 'import vtk;'
[llnguyen@h2 ~]$
```

Using the same vtk installation, same python installation and runScript.sh from the older version of compucell3d does not throw the "No module named vtk" error. Thoughts?

**Comment by CompuCell3D** [comment]
Can you post the content of `/N/soft/rhel6/compucell3d/3.7.9/runScript.sh` ?

**Comment by lemaiw** [comment]
Hello, hope your weekend went well!

Thanks for your response, it was an excellent clue and I managed to overcome that vtk hurdle. In short, it looks like runScript.sh was taking control of my pathing so I took it back from runScript.sh ;-) I suspect I did that in the older installation, hence the lack of vtk errors there.

I have a separate question now regarding the same guy runScript.sh (or more specifically CompuCellPythonSimulationCML.py), namely it whines about PyQt5.QtCore not existing. A cursory look at your commits looks like you're trying to remove this dependency for cases like mine, namely installation on a cluster. I went ahead and commented out the lines in CompuCellPythonSimulationCML.py that involved importing those PyQt5 modules, ran runScript.sh against some demo files and it seems to go through. Any thoughts there? Is this how it's supposed to behave or have I done some magic I wasn't supposed to?

Let me know if I should file a separate issue for better tracking! Thanks again for the response.

**Comment by CompuCell3D** [comment]
This is good. I think the dependence on PyQt5 in CompuCellPythonSimulationCML.py was a leftover and in fact was PyQt5 not used anywhere in the code that was executed via CompuCellPythonSimulationCML.py

As a heads up we are cleaning up a lot of code and moving to Python 3 in upcoming release so will not spend too much time cleaning up old stuff like  CompuCellPythonSimulationCML.py. We will patch bugs in the 3.7xxx branches but really we are looking forward to the new code-base.

**Comment by lemaiw** [comment]
Thank you for the heads up. I am got these PyQt5 errors now when trying to run `bash compucell3d.sh` - but it seems that this might be a hard requirement there and might be elsewhere but given the fact that you're moving to Python 3 and a new release, I'm gonna surmise this won't be cleaned up either any time soon, yes? ;-)

Thanks for the info, I'll let the requestor of the installation (who I believe originally developed this code) know. I'll see if perhaps the precompiled binaries work out.

**Comment by CompuCell3D** [comment]
Yes this could happen but here is one thing you can when you edit  ` CompuCellPythonSimulationCML.py` instead of commenting PyQt5 import statements you can do try-except block  :
```
try:
    from PyQt5.Core import *
except ImportError:
    pass
```

**Comment by CompuCell3D** [comment]
Closing the issue for now. We are moving to 4.0.0 branch and Python 3-based CC3D 4.0.0 so all issues should be tested against this branch
