### ISSUE TITLE
Random Seed to Investigate Faults, Errors and Crashes

### ISSUE THREAD

**Issue by zafarali** [CompuCell3D/CompuCell3D#12]
Hi, 

Is there any way to obtain and fix the seed being used by the random number generator in CC3D?
I am experiencing segmentation faults , bus errors and random crashes and would like to investigate if it is due to certain seeds or a problem with the code.

Some errors I have received:

1. 
```
END OF SIMULATION  
emiting finish request
11217.7 ms spent in solving diffusion problem
./compucell3d.command: line 125:   583 Segmentation fault: 11  ${PYTHON_EXEC} ${PREFIX_CC3D}/player/compucell3d.pyw $* --currentDir=${PREFIX_CC3D}
```

2.
```
terminate called after throwing an instance of 'BasicException'
./compucell3d.command: line 125:  3309 Abort trap: 6           ${PYTHON_EXEC} ${PREFIX_CC3D}/player/compucell3d.pyw $* --currentDir=${PREFIX_CC3D}
```

3.
```
./compucell3d.command: line 125:  1514 Bus error: 10           ${PYTHON_EXEC} ${PREFIX_CC3D}/player/compucell3d.pyw $* --currentDir=${PREFIX_CC3D}
```

4.
```
./compucell3d.command: line 125:   685 Segmentation fault: 11  ${PYTHON_EXEC} ${PREFIX_CC3D}/player/compucell3d.pyw $* --currentDir=${PREFIX_CC3D}
```

documenting this progress at:
zafarali/metastasis#5

**Comment by maciekswat** [comment]
I dont think random seed has anything to do with it. Is there any chance you could send me a simple version of the simulation with the segfault?

**Comment by zafarali** [comment]
Sorry, I was being vague.

The crashing seems to be sporadic and unpredictable, this is why to produce a reproducible crash and show you a minimal version, I wanted to use a constant random seed between runs to see if crashing then becomes consistent. This is why I asked if there was a way to do this.

**Comment by maciekswat** [comment]
In that case in the <Potts> section put

<RandomSeed>1232232</RandomSeed>

and this should do the trick. However if you use Python random number generator  you would need to seed it appropriately in Python script

**Comment by zafarali** [comment]
I'm sorry, which section do I put this in?

Yes, I will handle the python number generator.

**Comment by maciekswat** [comment]
You have to put it in the Potts Section (for some reason github does not allow pasting XML snippets here)

The tag is RandomSeed

<RandomSeed>12323232</RandomSeed>

**Comment by maciekswat** [comment]
check Demos/BookChapterDemos_ComputationalMethodsInCellBiology/VascularTumor/Simulation/VascularTumor.xml

**Comment by zafarali** [comment]
Thank you, I was not able to replicate the error.
