### ISSUE TITLE
[BUG] self.stopSimulation() doesn't call steppable.finish()

### ISSUE THREAD

**Issue by zafarali** [CompuCell3D/CompuCell3D#15]
Hi,

I noticed that calling `self.stopSimulation()` in a steppable does not call the `finish()` for the registered steppables. Is this a deliberate design decision? I would assume that `finish()` runs regardless of how the simulation has been ended.

**Comment by tjsego** [comment]
@CompuCell3D this is resolved by #287. Can we close this?
