### ISSUE TITLE
Add option to name VTK on batch-run

### ISSUE THREAD

**Issue by JulianoGianlupi** [CompuCell3D/CompuCell3D#165]
CC3D 3.7.4 had an option to set vtk names, it has been asked to bring it back

**Comment by tjsego** [comment]
We can add back the command line argument if so desired, but the functionality still exists in 4.1.0. It can be accomplished in the python steppable with the following code: 
```
def step(self,mcs):
        cml_field_handler = CompuCellSetup.persistent_globals.cml_field_handler
        if cml_field_handler is not None: 
                cml_field_handler.output_file_core_name = "new_vtk_core_name_HERE"
```
Here VTK output is saved with prefix "new_vtk_core_name_HERE" at a frequency specified by the command line argument "--output-frequency" relative to the output directory path, which can also be set in the python steppable with the following code: 
```
from cc3d.CompuCellSetup import simulation_utils
class mySteppable(SteppableBasePy):
        def __init__(self,frequency=1): 
                simulation_utils.set_output_dir(abs_output_dir)
```
Here the absolute path of the output directory is "abs_output_dir". With the changes in https://github.com/CompuCell3D/CompuCell3D/commit/0b8e0d79854561ac31c0c000a0daf01bb1b8bf36, I was able to call and simulate multiple instances of the same project in parallel with a custom vtk output prefix and multiple restart snapshots on Windows. The only other necessary trick is to have the steppable declare a unique output directory per instance of the simulation. In the steppable, this looks like 
```
from cc3d.CompuCellSetup import simulation_utils
import os
class mySteppable(SteppableBasePy):
        def __init__(self,frequency=1):
                run_count = 1
                while True:
                        output_dir_str = abs_output_dir + str(run_count)
                        output_dir = os.path.abspath(output_dir_str)
                        if not os.path.exists(output_dir):
                                break
                        else:
                                run_count += 1

                simulation_utils.set_output_dir(output_dir)
```

**Comment by JulianoGianlupi** [comment]
We need to check that the manual explains how to name the vtks (I didn't find anything about it). 

I feel that people will get use out of the command line option, using the cluster queuing system to name them or something else. So we should put it back (our EPA collaborators seemed to get value from it).

**Comment by tjsego** [comment]
Sounds good. See https://github.com/CompuCell3D/CompuCell3D/commit/996a71b1124e875c892d747609fbd467c0312fee

Also, let's add a brief tutorial in the next manual on how to do this in python.

**Comment by JulianoGianlupi** [comment]
Ability to name VTK with command line added in PR #168
