### ISSUE TITLE
Hover info is wrong in Player preferences

### ISSUE THREAD

**Issue by tjsego** [CompuCell3D/CompuCell3D#169]

**Comment by jpsluka** [comment]
![wrong_mouse_over_text](https://user-images.githubusercontent.com/22944062/69354572-5027f600-0c4e-11ea-80f2-765417437217.png)
CC3D v 4.0.0
Windows 7

In player's preferences window the buttons etc. have hover-over text. They all appear to be the same. In the attached image the mouse is over the "=Project" checkbox. The popup text is not correct. The same popup text is shown for every element in the window.

**Comment by CompuCell3D** [comment]
Fixed
