### ISSUE TITLE
CC3D Restart doesn't appear to work

### ISSUE THREAD

**Issue by jpsluka** [CompuCell3D/CompuCell3D#170]
CC3D v 4.0.0, Windows 7

The restart capability does not appear to work. 
https://www.reddit.com/r/CompuCell3D/comments/dwd9bv/potential_bug/

There may be a problem with  the RestartManager.py file at lines 902 and 923, which gives the key error for "neighbor_id". Editing the file and replacing "neighbor_id" with "neighborIds" in lines like;
           neighbor_ids = fpp_dict['neighborIds']

changes the crash to just after these lines in the console log;
       GOT SUSTOM SETTINGS : C:\Users\James Sluka\CC3DWorkspace    
             \tumor_3d_cc3d_11_20_2019_14_55_14\restart_000120\Simulation\_settings.sqlite

I tried restarting the demo at C:\CompuCell3D-py3-64bit\Demos\PluginDemos\FPPDemo\.

**Comment by jpsluka** [comment]
The original bug report was for a simulation that had FPP's. I've also tested with the FPPDemo from the demos folder.

**Comment by jpsluka** [comment]
I've tried two other demos;
C:\CompuCell3D-py3-64bit\Demos\BookChapterDemos_ComputationalMethodsInCellBiology\cellsorting\
and
C:\CompuCell3D-py3-64bit\Demos\PluginDemos\ContactLocalProduct\ContactLocalProductExample\
both seem to restart correctly. So this may be specific to restarting simulations with FPP.

**Comment by CompuCell3D** [comment]
This issue is fixed in master. We will make it available with the new version of CC3D. . We will make this release soon
