### ISSUE TITLE
PIFF writer steppable is using the wrong directory

### ISSUE THREAD

**Issue by jpsluka** [CompuCell3D/CompuCell3D#171]
CC3D v4.0.0, Windows 7

The PIFF writer steppable is writing the output files to the top level CC3D directory. It probably should be writing to the project folder for the run. The code also appears to ignore a path in the file name, and if a path is present, the output can't be found.

See:
https://www.reddit.com/r/CompuCell3D/comments/dztm3z/steppable_pifdumper_not_working/

Code snippet, edited version of what Twedit++ supplies:
    <Steppable Frequency="100" Type="PIFDumper">
       <PIFName>Bobby</PIFName>
       <PIFFileExtension>piff</PIFFileExtension>
    </Steppable>

The piff files are written to my top level CC3D directory "C:\CompuCell3D-py3-64bit"

**Comment by CompuCell3D** [comment]
Fixed
