### ISSUE TITLE
add python API to take on-demand screenshots

### ISSUE THREAD

**Issue by CompuCell3D** [CompuCell3D/CompuCell3D#187]
include resolution in int API

**Comment by gabroo** [comment]
@maciekswat I tried using this and it works (after generating `screenshots.json` from GUI) however when I make changes to the `"TypeColorMap"` property in the file cc3d does not recognize this, it only responds to changes in player5 Configuration class

**Comment by maciekswat** [comment]
closing this issue and reopening another one
