### ISSUE TITLE
Version 4.1.1 wont run on Mac OS 10.15.x

### ISSUE THREAD

**Issue by jpsluka** [CompuCell3D/CompuCell3D#201]
There is a problem with persuading OX 10.15.x to run version 4.1.1. It is no longer possible to change the Mac OS Security & Privacy settings to allow apps downloaded from Anywhere. The new Mac system is supposed to allow exceptions but it doesn't appear to work with Twedit++. Though the .command file can be allowed, it then stops at the twedit++.pso file.

The only solution I've found is to turn off the new parts of the Mac's security. In a command window:
`sudo spctl --master-disable`

After doing the above the Security & Privacy window has returned the previous "Anywhere" option.

Not sure if the above fix gets undone if you logoff or restart the Mac.

**Comment by maciekswat** [comment]
This is already solved with new binaries that are signed and notarized
