### ISSUE TITLE
Demos using DiffusionSolverFE include DoNotDiffuseTo

### ISSUE THREAD

**Issue by jpsluka** [CompuCell3D/CompuCell3D#203]
Demos using DiffusionSolverFE include <DoNotDiffuseTo> tags that are commented out. DiffusionSolverFE does not appear to support this tag so they should be removed from the demos. The same may be true for the <DoNotDecayIn> tags.

C:\CompuCell3D-py3-64bit\Demos\SteppableDemos\DiffusionSolverFE\diffusion_2D_scale\

```
    <Steppable Type="DiffusionSolverFE">
        <DiffusionField>
            <DiffusionData>
                <FieldName>FGF</FieldName>
                <DiffusionConstant>1.05</DiffusionConstant>
                <DecayConstant>0.0000</DecayConstant>
                <!--DoNotDecayIn>Medium</DoNotDecayIn-->
                <!--DoNotDiffuseTo>Bacteria</DoNotDiffuseTo-->
            </DiffusionData>
            <SecretionData>
                <Secretion Type="Amoeba">0.2</Secretion>
            </SecretionData>
        </DiffusionField>
    </Steppable>
```

**Comment by tjsego** [comment]
Agreed. https://github.com/CompuCell3D/CompuCell3D/pull/215 will make this option obsolete in DiffusionSolverFE and ReactionDiffusionSolverFE, anyway.

**Comment by maciekswat** [comment]
Fixed
