### ISSUE TITLE
Twedit++ inserts incorrect inits for extra fields

### ISSUE THREAD

**Issue by jpsluka** [CompuCell3D/CompuCell3D#210]
CC3D 4.1.1. Twedit++ [CC3D Python][Extra Fields][Scalar Field Pixel Level - Create] inserts the correct python code snippet but also inserts:
```
from PlayerPython import * 
import CompuCellSetup
```
at the top of the python file. These imports cause Player to crash.

Other Twedit helpers relating to extra fields may have the same problem.

**Comment by tjsego** [comment]
Fixed by https://github.com/CompuCell3D/CompuCell3D/pull/206.
