### ISSUE TITLE
No help on "dictionary" in the online doc's

### ISSUE THREAD

**Issue by jpsluka** [CompuCell3D/CompuCell3D#218]
The online documentation/help at https://compucell3d.readthedocs.io/en/latest/index.html
Searching with "dictionary" doesn't find anything. There is no online help for CC3D dictionaries?

**Comment by tjsego** [comment]
For CC3D-specific Python dictionaries, documentation is in the [Python Scripting Manual for CompuCell3D](https://pythonscriptingmanual.readthedocs.io/en/latest/index.html). Is this what you're looking for?

**Comment by jpsluka** [comment]
So we have multiple online docs?

https://compucell3d.readthedocs.io/en/latest/

https://pythonscriptingmanual.readthedocs.io/en/latest/

Are there any others?

 

I notice these online doc’s are not linked on the www.compucell3d.org/Manuals web page. I’ll add links.

**Comment by jpsluka** [comment]
Ah, I see them now. Sure would be nice to have a single online manual, or at least be able to search across all the manuals.

**Comment by tjsego** [comment]
> Ah, I see them now. Sure would be nice to have a single online manual, or at least be able to search across all the manuals. 

Agreed. We could merge all content into one big manual and treat the different current manuals as sections, but eliminating all the redundant content could potentially be a major project. 

Are we OK to close this issue?

**Comment by jpsluka** [comment]
Yes, close it
