### ISSUE TITLE
[BUG] I/O related random segfaults

### ISSUE THREAD

**Issue by glyg** [CompuCell3D/CompuCell3D#22]
Hi,

I experience segmentation faults at the end of simulation when writing some data to a file. The bug is not very reproducible. It might happen e.g. after I ran the simulation three times.

Here is an example of a steppable producing the segfault:

``` python
class RegisterSteppable(SteppableBasePy):
    ''' Class governing cell growth steps.

    '''

    def __init__(self, _simulator, _frequency=1):

        SteppableBasePy.__init__(self, _simulator, _frequency)

    def start(self):
        self.cell_data = []

        self.cell_columns = ['mcs', 'id',
                             'type', 'age', 'P_sr',
                             'n_type1', 'n_type2', # Number of neighbors by types
                             'a_type1', 'a_type2'] # Total contact area by types

    def step(self, mcs):

        for cell in self.cellList:
            n_type1 = 0
            n_type2 = 0
            a_type1 = 0
            a_type2 = 0

            for neighbor, contact_area in self.getCellNeighborDataList(cell):
                if neighbor is None: # Medium
                    continue
                if neighbor.type == 1:
                    n_type1 += 1
                    a_type1 += contact_area
                elif neighbor.type == 2:
                    n_type2 += 1
                    a_type2 += contact_area

            cellDict = self.getDictionaryAttribute(cell)

            step_data = [mcs, cell.id,
                         cell.type,
                         cellDict['age'],
                         cellDict['P_sr'],
                         n_type1, n_type2,
                         a_type1, a_type2]
            self.cell_data.append(step_data)

    def finish(self):

        # sim_dir = CompuCellSetup.getSimulationOutputDir()

        timestamp = datetime.datetime.now().__str__()
        timestamp = timestamp.replace(' ','-')
        timestamp = timestamp.replace('.','-')
        timestamp = timestamp.replace(':','-')

        full_fname = '/home/guillaume/Bureau/sim_cell_data_%s.csv' %timestamp
        metadata = full_fname
        col_names = ','.join(self.cell_columns)
        header = '\n'.join([metadata, col_names])
         np.savetxt(full_fname, np.asarray(self.cell_data),
                    header=col_names, delimiter=',')

         print('saved sim cell data to {}'.format(full_fname))

```

Commenting out the `np.savetxt` line removes the segfault, that also happens with the file opening mechanism provided in the docs, or during parameter scans.

Best,

Guillaume

**Comment by maciekswat** [comment]
Which platform are you running it on? How often does this happen (roughly?)
On 2/9/2016 3:38 AM, Guillaume Gay wrote:
>
> Hi,
>
> I experience segmentation faults at the end of simulation when writing 
> some data to a file. The bug is not very reproducible. It might happen 
> e.g. after I ran the simulation three times.
>
> Here is an example of a steppable producing the segfault:
>
> class  RegisterSteppable(SteppableBasePy):
>      ''' Class governing cell growth steps.
>
> '''
>
>      def  __init__(self,_simulator,_frequency=1):
>
>          SteppableBasePy.__init__(self, _simulator, _frequency)
>
>      def  start(self):
>          self.cell_data=  []
>
>          self.cell_columns=  ['mcs','id',
>                               'type','age','P_sr',
>                               'n_type1','n_type2',# Number of neighbors by types
>                               'a_type1','a_type2']# Total contact area by types
>
>      def  step(self,mcs):
>
>          for  cellin  self.cellList:
>              n_type1=  0
>              n_type2=  0
>              a_type1=  0
>              a_type2=  0
>
>              for  neighbor, contact_areain  self.getCellNeighborDataList(cell):
>                  if  neighboris  None:# Medium
>                      continue
>                  if  neighbor.type==  1:
>                      n_type1+=  1
>                      a_type1+=  contact_area
>                  elif  neighbor.type==  2:
>                      n_type2+=  1
>                      a_type2+=  contact_area
>
>              cellDict=  self.getDictionaryAttribute(cell)
>
>              step_data=  [mcs, cell.id,
>                           cell.type,
>                           cellDict['age'],
>                           cellDict['P_sr'],
>                           n_type1, n_type2,
>                           a_type1, a_type2]
>              self.cell_data.append(step_data)
>
>      def  finish(self):
>
>          # sim_dir = CompuCellSetup.getSimulationOutputDir()
>
>          timestamp=  datetime.datetime.now().__str__()
>          timestamp=  timestamp.replace(' ','-')
>          timestamp=  timestamp.replace('.','-')
>          timestamp=  timestamp.replace(':','-')
>
>          full_fname=  '/home/guillaume/Bureau/sim_cell_data_%s.csv'  %timestamp
>          metadata=  full_fname
>          col_names=  ','.join(self.cell_columns)
>          header=  '\n'.join([metadata, col_names])
>           np.savetxt(full_fname, np.asarray(self.cell_data),
>                      header=col_names,delimiter=',')
>
>           print('saved sim cell data to {}'.format(full_fname))
>
> Commenting out the |np.savetxt| line removes the segfault, that also 
> happens with the file opening mechanism provided in the docs, or 
> during parameter scans.
>
> Best,
>
> Guillaume
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/CompuCell3D/CompuCell3D/issues/22>.
>


-- 
Maciej Swat

Biocomplexity Institute, Indiana University,

Simon Hall MSB1, 043D
212 S. Hawthorne Drive
Bloomington, IN  47405-7003

e-mail: mswat@indiana.edu
phone: (812) 855-2441
fax (812) 855-5533

**Comment by glyg** [comment]
Hi Maciej,

Sorry I forgot to give the sys info

This is on Linux Mint 17.2 based on ubuntu 15.10 (64 bits), with the system's python 2.7.6 and libstdc++.so.6.0.21

It happens every 3 runs (typ.) of the simulation.

**Comment by glyg** [comment]
Hi, closing this, as both OS and python version are very outdated now.
