### ISSUE TITLE
consider conda-packiging CC3D 

### ISSUE THREAD

**Issue by CompuCell3D** [CompuCell3D/CompuCell3D#237]

**Comment by tjsego** [comment]
Mostly accomplished in [feature/install_config](https://github.com/CompuCell3D/CompuCell3D/tree/feature/install_config). Holding off on the PR until after the upcoming release.

**Comment by tjsego** [comment]
Addressed in #501.

**Comment by tjsego** [comment]
Done in #501. Closing.
