### ISSUE TITLE
CC3D Player crashes upon trying to play latticedata dml file

### ISSUE THREAD

**Issue by sup27606** [CompuCell3D/CompuCell3D#239]
This is the latest version 4.2. My system: Mac OS Catalina 10.15.4. The player crashes when I hit play after loading a latticedata dml file. Here are the error messages:

 Traceback (most recent call last):
  File "/Applications/CC3D_4.2.0/lib/site-packages/cc3d/player5/Plugins/ViewManagerPlugins/SimpleTabView.py", line 1802, in __runSim
    prepare_flag = self.prepareSimulation()
  File "/Applications/CC3D_4.2.0/lib/site-packages/cc3d/player5/Plugins/ViewManagerPlugins/SimpleTabView.py", line 1719, in prepareSimulation
    self.customSettingPath = self.cc3dSimulationDataHandler.cc3dSimulationData.custom_settings_path
AttributeError: 'NoneType' object has no attribute 'cc3dSimulationData'
CLOSING LOCAL SOCKET

**Comment by CompuCell3D** [comment]
Thanks for the report. We fixed it in feature/4.2.0_fixes branch. For now though you may patch SimpleTabView.py file with this one 

https://github.com/CompuCell3D/CompuCell3D/blob/feature/4.2.0_fixes/cc3d/player5/Plugins/ViewManagerPlugins/SimpleTabView.py

Simply copy the above file to /Applications/CC3D_4.2.0/lib/site-packages/cc3d/player5/Plugins/ViewManagerPlugins/SimpleTabView.py 

This should provide immediate fix for the problem. We will release updated binaries soon. Let me know if this works for you

**Comment by sup27606** [comment]
Hi,This fix works! Thank you very much. Now the player opens and plays the simulation, but if I switch between different views, i.e. cell view to field view several times during the playing, the player crashes. Here is the error message:
/Applications/CC3D_4.2.0/compucell3d.command: line 64: 98488 Segmentation fault: 11  ${PYTHON_EXEC} ${PREFIX_CC3D}/lib/site-packages/cc3d/player5/compucell3d.pyw $* --currentDir=${PREFIX_CC3D}
Also, I cannot open multiple graphics windows to see two views from the same simulation, e.g. cell and field views side by side. I can do it when running a live simulation, but not in the player mode. Other than these issues, the player works well now.
Thanks so much,Supriyo
    On Friday, May 8, 2020, 06:26:29 PM PDT, CompuCell3D <notifications@github.com> wrote:  
 
 


Thanks for the report. We fixed it in feature/4.2.0_fixes branch. For now though you may patch SimpleTabView.py file with this one

https://github.com/CompuCell3D/CompuCell3D/blob/feature/4.2.0_fixes/cc3d/player5/Plugins/ViewManagerPlugins/SimpleTabView.py

Simply copy the above file to /Applications/CC3D_4.2.0/lib/site-packages/cc3d/player5/Plugins/ViewManagerPlugins/SimpleTabView.py

This should provide immediate fix for the problem. We will release updated binaries soon. Let me know if this works for you

**Comment by CompuCell3D** [comment]
Quick question: when you say "but if I switch between different views, i.e. cell view to field view several times during the playing, the player crashes" does that mean that this issue exists during replay of .dml file or when actual simulation is running?

**Comment by sup27606** [comment]
No, this is only while playing. During simulation, the issue isn’t there.
Best,Supriyo


Sent from Yahoo Mail for iPad


On Monday, May 11, 2020, 8:13 PM, CompuCell3D <notifications@github.com> wrote:




Quick question: when you say "but if I switch between different views, i.e. cell view to field view several times during the playing, the player crashes" does that mean that this issue exists during replay of .dml file or when actual simulation is running?

**Comment by CompuCell3D** [comment]
All problems reported here should be fixed in the new 4.2.1 version . See release candidate  https://sourceforge.net/projects/cc3d/files/4.2.1-release-candidate/ 

Thanks for reporting the bug
