### ISSUE TITLE
Parameter estimation in CC3D

### ISSUE THREAD

**Issue by nadaa** [CompuCell3D/CompuCell3D#25]
Hi,
I have a CC3D model with more than 10 parameters, and I want to write some code to estimate few sensitive  parameters values based on experimental data. However, I still don't have much experience in CC3D development. Thus I need some advice. I have the following questions in mind:

-How is it easy to interrupt and reestablish the simulation with adapted parameters values?
-How to  integrate additional code into CC3D?.  
-I've read that parameters in CC3D are dependent!. Is that mean I shall change all parameters at once?

I don't know if this is the right place to ask these questions!. If not I do apologize.

Regards,
Nada

**Comment by maciekswat** [comment]
On 9/17/2016 5:25 PM, nadaa wrote:
>
> Hi,
> I have a CC3D model with more than 10 parameters, and I want to write 
> some code to estimate few sensitive parameters values based on 
> experimental data. However, I still don't have much experience in CC3D 
> development. Thus I need some advice. I have the following questions 
> in mind:
>
> -How is it easy to interrupt and reestablish the simulation with 
> adapted parameters values?
>
Quite easy. It depends what you really want to accomplish and whether 
you will have a code that will examine current state of the simulation 
and interrupt it if you decide that there is no point running simulation 
any further.
Typically what you wanna do is to run parameter scan - see
http://www.compucell3d.org/BinDoc/cc3d_binaries/Manuals/PythonScriptingManual_v.3.7.5.pdf

page 60

Right now we are supporting exhaustive grid parameter scans and what you 
can do in your code is to have a steppable that interrupts a simulation 
when certain conditions are met.

To interrupt simulation from a steppable, use:

self.stopSimulation()

> -How to integrate additional code into CC3D?.
>

Do you mean C++ or Python code?
>
>
> -I've read that parameters in CC3D are dependent!. Is that mean I 
> shall change all parameters at once?
>

Yes this is not a CC3D problem this is the property of Cellular Potts 
model (and many other cell based models). For example when you change 
contact energy you may also change parameters of volume energy 
constraint to e.g. prevent cells from disappearing.

take a look at this write-up that should give you an idea of how one 
actually would choose parameters for a given CPM-based simulation:

http://www.compucell3d.org/Workshops/Workshop11/Materials/AbbasHowTo

Let me know if you have more questions

**Comment by nadaa** [comment]
Thanks maciekswat.
I have a concern regarding parameters . I'm working on a model which involves the processes of cells mitosis and apopotosis . I want to know which parameters are related mitosis and apoptosis?

Are there are specific parameters for mitosis & apoptosis. There are already classes were added to a steppable. Still there is no  parameters!

 I want to have two parameters added to the model one for cell mitosis and the other for cell apoptosis , then apply parameters estimation to search for their best values. 

Any suggestions?

Regards,
Nada

**Comment by maciekswat** [comment]
The only parameters that we use to parameterize mitosis are:
doubling volume
and the attributes of the parent and daughter cells after the mitosis.

What are the parameters you added to mitosis and apoptosis?

Are you looking to do parameter scan involving your paramters defined in
Python?

**Comment by nadaa** [comment]
I'm thinking to add two parameters to represent mitosis rate and apoptosis rate.
Since mitosis and apoptosis are changing over time , those values will be changed in each MCS.( I still don't have a clear scenario).

Is it possible to run parameter scan in python? 
I have experimental data, I want to calibrate parameters based on it.

**Comment by maciekswat** [comment]
Yes it is easy to run parameter scan over parameters defined in the 
Python scripts. Once you have an idea what those parameters will be let 
me know and I will help you set this up


M

**Comment by nadaa** [comment]
Thanks.
How I can  run the simulation totally from python?

**Comment by maciekswat** [comment]
http://www.compucell3d.org/BinDoc/cc3d_binaries/Manuals/PythonScriptingManual_v.3.7.5.pdf

page 60-70 explains in detail how to do this. Briefly -you configure parameter scans using Twedit++ and then run it however you like - either using guy or from command line. You can scan over parameters defined in XML and/or Python.
-- 
Maciej Swat

Biocomplexity Institute, Indiana University,

Simon Hall MSB1, 043D
212 S. Hawthorne Drive
Bloomington, IN  47405-7003

e-mail: mswat@indiana.edu
phone: (812) 855-2441
fax: (812) 855-5533

**Comment by tjsego** [comment]
Addressed. Closing.
