### ISSUE TITLE
Player not saving state of windows

### ISSUE THREAD

**Issue by jpsluka** [CompuCell3D/CompuCell3D#252]
Player does not seem to save the existence and location of extra display windows. Adding a window, clicking the camera icon (or not), starting, stopping, restarting, ... nothing seems to trigger writing the player state to the _settings.sqlite file. If the sim is restarted in the same player window the other windows are removed. If the player is restarted it also forgets about the other windows.

Player 4.2.0, Windows 10

**Comment by jpsluka** [comment]
This seems to be a bug introduced fairly recently, perhaps in or after 4.1.x. This is really confusing people in the Covid19 workshop since they have to reset the state of the  player window for every simulations run; not leaving player, just hitting stop then run trashes the window layout.

**Comment by jpsluka** [comment]
Player version 4.1.1 on nanoHUB remembers what windows exist but if you run, change windows, run, stop, start it loses the window's positions.

**Comment by jpsluka** [comment]
This may be related to issue #223 

If the hidden sqlite file is to be used it must be carefully constructed. I notice that if the file is deleted then it is recreated when payer is run. Where is that info coming from? Is it from another file somewhere in the distribution directory or from the current state of Player? Furthermore, it appears the hidden file is re-read every time a simulation is started in player, including repeat run of the same simulation within a particular player instance. 

It is possible to get this file into such a state the the 'display output" and "show terminal in player" options are out of synch and unfixable except by deleting the hidden sqlite file. 

This is the second time a corruption of this sqlite file has made player unusable and required hours of effort to chase down. (The 2nd error is where no output from python print statements was being shown.)

**Comment by jpsluka** [comment]
This may also be related to issue #113

**Comment by CompuCell3D** [comment]
What if you remove .sqllite before you run covid-19 simulation? Then you can open various windows and see it their state is being saved. I wonder if this has to do with using windows generated .sqllite file on linux

**Comment by CompuCell3D** [comment]
Also for window position saving to work users need to press "Stop" button. This is when windows are saved. Probably not the most convenient but this is how saving of windows position works currently. We could add new feature where we save windows on any type of exit from CC3D and once the simulation is finished. This would make more sense.

**Comment by jpsluka** [comment]
The "stop" only seems to work sometime. For one sim I tried it works correctly, start sim, add windows, make'm pretty, continue run, stop. Run (e.g. a restart of the sim since it was stopped and not paused) and windows are where they should be. For other sims this does not work. Running the CV19 sim, start, a few steps, tile the windows (there are a lot), continue run, stop. Run... windows in the wrong place. I'll email a video (if I can) to Swat & TJ

**Comment by CompuCell3D** [comment]
Fixed

**Comment by jpsluka** [comment]
Still having occasional problems that appear to be linked to corrupt sqlite files. Occasionally, Player will get into a mode where launching from twedit++ opens player, it thinks for a few seconds, then shuts down without any error message. Deleting the project's sqlite file and the hidden users sqlite file appears to fix this.
