### ISSUE TITLE
on-demand screenshots API does not respect TypeColorMap property of screenshots.json file

### ISSUE THREAD

**Issue by gabroo** [CompuCell3D/CompuCell3D#259]
changing colors in this map does not change the colors in resultant screenshots

**Comment by CompuCell3D** [comment]
Could you post a simple simulation showing this issue along wtih json file?

**Comment by CompuCell3D** [comment]
To do - store lookup tables for screenshots to avoid generating it each time screenshot is taken

**Comment by CompuCell3D** [comment]
Fixed
