### ISSUE TITLE
Version number doesn't show up inn Player in the Help - Check for CC3D Updates

### ISSUE THREAD

**Issue by jpsluka** [CompuCell3D/CompuCell3D#260]
The Players "Check for CC3D Updates" gives the version number as "None rev.None" and doesn't have anything listed for recent features.

![image](https://user-images.githubusercontent.com/22944062/85059751-28602880-b172-11ea-9f53-3b78083901ff.png)

Windows 10, CC3D version 4.2.0

**Comment by CompuCell3D** [comment]
Fixed the issue - this was caused by migration of CC3D site and the (too) simple code we had previously to fetch the new version information

**Comment by CompuCell3D** [comment]
Fixed
