### ISSUE TITLE
Add saving windows layout on close / simulation stop / simulation finish

### ISSUE THREAD

**Issue by CompuCell3D** [CompuCell3D/CompuCell3D#269]
windows layout should be saved if we close window or if the simulation finishes

**Comment by CompuCell3D** [comment]
Decided not to save layout on Player close. If we save simulation layout on stop and simulation finish this is sufficient. It is better to have some way of exiting Player without saving layout - this is what close butting provides

**Comment by jpsluka** [comment]
Perhaps what we should do is the player only loads the config when the simulation is loaded. Currently it is loaded every time the run button is clicked, which immediately overwrites any changes to the GUI layout that the user just made.

**Comment by CompuCell3D** [comment]
We may consider this but now with the fix it looks like settings behave in a more sensible way than before

**Comment by CompuCell3D** [comment]
Fixed
