### ISSUE TITLE
change name simulation output directory

### ISSUE THREAD

**Issue by nadaa** [CompuCell3D/CompuCell3D#27]
Hi,

I want to change the name of output directory (simulation name_cc3d_month_day_year_#_#_#) of each simulation. Instead ,it can be as (simulation name_ Simulation num), from where I can do that?

Thanks

**Comment by MasterKarinski** [comment]
Very good question! I'm also interested in this issue!!

**Comment by CompuCell3D** [comment]
I have added this option to the master branch - If you are building CC3D you may checkout master branch, build CC3D and this feature will be there. If you do not want to build CC3D replace the following Python files in your existing CC3D installation dir
1.
player/CompuCellPythonSimulationCML.py 
with 
https://github.com/CompuCell3D/CompuCell3D/blob/e03dd0984c68d0c42f4f9478f997b46a35b33819/CompuCell3D/core/pythonSetupScripts/CompuCellPythonSimulationCML.py

2. 
pythonSetupScripts/CompuCellSetup.py
with 
https://github.com/CompuCell3D/CompuCell3D/blob/e03dd0984c68d0c42f4f9478f997b46a35b33819/CompuCell3D/core/pythonSetupScripts/CompuCellSetup.py

3.
player/Plugins/ViewManagerPlugins/SimpleTabView.py
with
https://github.com/CompuCell3D/CompuCell3D/blob/e03dd0984c68d0c42f4f9478f997b46a35b33819/CompuCell3D/player/Plugins/ViewManagerPlugins/SimpleTabView.py


Let me know if this works for you

**Comment by tjsego** [comment]
Resolved. Closing.
