### ISSUE TITLE
stop_simulation does not call the finish methods

### ISSUE THREAD

**Issue by jpsluka** [CompuCell3D/CompuCell3D#286]
stop_simulation does not call the finish methods.
Should it?

**Comment by CompuCell3D** [comment]
no it should not call finish method. Finish method is called after simulation fully completes i.e. after all MCS

**Comment by jpsluka** [comment]
Why? If a simulation has a logical stopping point (like the number of cells exceed a threshold) then stop_simulation should be used. But if finish is used to write output, close files etc. then the finish are not called.

You could reassign the maximum number of mcs so the sim always finishes through finish functions but just have stop_simulation do it makes more sense.

As it stand now stop_simulation appears to basically be an error exit, that is, it exits the simulation in a non-standard way.

**Comment by CompuCell3D** [comment]
Finish was designed to operate like that but if you want to use functionality you are describing this would do the trick: 
``` 
if cell_count > threshold:
        # call finish
        self.finish()
        self.stop_simulation()
```

Let me know if this makes sense

**Comment by jpsluka** [comment]
Wouldn't that only call the finish for that particular steppable? If you have more than one steppable the other finishes wouldn't get called.

**Comment by CompuCell3D** [comment]
So in the case you are describing we could add `on_stop` function. I think this would be a cleaner solution where every steppable defining this function would be called. I will add this functionality now.

**Comment by CompuCell3D** [comment]
Ok, I issued PR  + added an example . I think this solultion with `on_stop` callback function is the one we want

**Comment by jpsluka** [comment]
Not sure how this would work. Would each steppable now need both a "finish" and an "on_stop" object? The goal is to be able to programmatically force a "normal exit" that is identical to the exit produced when the MCS limit is reached.

It might be easier to just say the preferred method is to have the code change the target number of mcs; e.g.,
     self.set_max_mcs(mcs)
I checked and this does appear to work correctly and calls all the individual steppables "finish".

**Comment by jpsluka** [comment]
So the current version's template for a steppable includes:
`    def finish(self):
        """
        Finish Function is called after the last MCS
        """
    def on_stop(self):
        # this gets called each time user stops simulation
        return
`
I don't think this adds much usable info. I would think users would probably just put a call to "finish" in the "on_stop". I still think stop_simulation should just, essentially, set max_mcs=mcs and therefore trigger all the steppables's finish's.

**Comment by CompuCell3D** [comment]
Fixed
