### ISSUE TITLE
closing the player after the simulation ends

### ISSUE THREAD

**Issue by nadaa** [CompuCell3D/CompuCell3D#29]
Hi,

Is there a function to call allow us to  close player once the simulation ends?

Thanks

**Comment by maciekswat** [comment]
When you open up the player go to “Preferences/settings “ Ctrl+, and on the output tab you will find “Close Player After The simulation” checkbox - check it. to make sure this works with the project you previously ran using Player, you first need to load the project (by clicking “Step” button) and then alter the settings as explained above. after you are done with he settings , close the player and from now on , after the simulation finishes the Player should close

Let me know if this works for you


-- 
Maciej Swat

Biocomplexity Institute, Indiana University,

Simon Hall MSB1, 043D
212 S. Hawthorne Drive
Bloomington, IN  47405-7003

e-mail: mswat@indiana.edu
phone: (812) 855-2441
fax: (812) 855-5533

**Comment by nadaa** [comment]
Yes, perfectly worked.

Thank you
