### ISSUE TITLE
Add a steppable template in twedit++

### ISSUE THREAD

**Issue by jpsluka** [CompuCell3D/CompuCell3D#291]
I don'[t see a steppable template in Twedit++. One that would create the basic framework of a steppable including the __init__, start, step and finish code. Perhaps could also add the proper lines in the main python file to register the steppable, or put that text in a comment when the steppable is added into the steppables file telling the user to move it to the other python file.

**Comment by tjsego** [comment]
This feature can be accessed in Twedit from the CC3D Simulation Window, by right-clicking on the item for the steppables script and selecting "Add Steppable..."

Can this issue be closed?

**Comment by jpsluka** [comment]
Yep! This would be a good hint for Juliano to add to his Twedit cheat sheet.

**Comment by JulianoGianlupi** [comment]
> 
> 
> Yep! This would be a good hint for Juliano to add to his Twedit cheat sheet.

It's there
