### ISSUE TITLE
Add decay constant to automatic scaling

### ISSUE THREAD

**Issue by tjsego** [CompuCell3D/CompuCell3D#292]
In flex PDE solvers, add decay constant criterion to determination of substeps: maximum stable decay constant = 1 - a small number.

**Comment by CompuCell3D** [comment]
How exactly we should scale this?

**Comment by CompuCell3D** [comment]
How exactly we should scale this?

**Comment by tjsego** [comment]
> How exactly we should scale this?

Similarly to current scaling by diffusion coefficient, in `DiffusionSolverFE::Scale()`. For scaling by decay constant, we can use a maximum stable decay constant of just less than 1.

**Comment by tjsego** [comment]
Resolved by #351
