### ISSUE TITLE
Fix XML commenting/unommenting 

### ISSUE THREAD

**Issue by CompuCell3D** [CompuCell3D/CompuCell3D#300]

**Comment by CompuCell3D** [comment]
Fix Block comment, so that when it encounters an XML comment it adds a <-- only at the beginning of the line and no --> at the end.
FIx block uncomment so it looks for <-- <--  ... -->and if it finds them removes only the <-- at the beginning and not the terminal -->

**Comment by CompuCell3D** [comment]
The comment problem in xml is serious. Some solutions:

1.       Other editors (like notepad++) have an xml plugin that properly comments comments and uncomments commented comments J.

2.       Probably easiest is to have CC3D load the entire XML file into a string and check its validity, throwing an  INFORMATIVE error message if there is a problem. As it is now there is no indication that there are commented comments. This could be done with a REGEX.

**Comment by tjsego** [comment]
> The comment problem in xml is serious. Some solutions:
> 
> 1. ```
>      Other editors (like notepad++) have an xml plugin that properly comments comments and uncomments commented comments J.
>    ```
> 2. ```
>      Probably easiest is to have CC3D load the entire XML file into a string and check its validity, throwing an  INFORMATIVE error message if there is a problem. As it is now there is no indication that there are commented comments. This could be done with a REGEX.
>    ```

The features on [features/contact_gui](https://github.com/CompuCell3D/CompuCell3D/tree/feature/contact_GUI) include CC3DML code scanning and real-time error reporting, 

![image](https://user-images.githubusercontent.com/21112182/89881199-2b383200-db93-11ea-9b2f-8d03071bbe4a.png)

You'll notice that the red block has a typo. This is detected by trying to parse the XML element, catching the error and then passing the error message for display. You'll also notice that a general error is reported in the bottom-left corner of the GUI. 

The scanner also graphically reports elements that are syntactically valid with no currently supported GUI tool (highlighted green), which is the main objective of this branch (to provide modular GUI code editors with automatic detection of downstream model effects). Hovering over a green XML element reports the recognized name and that no GUI tool is currently supported, 

![image](https://user-images.githubusercontent.com/21112182/89881222-34290380-db93-11ea-853b-41821a38dfc4.png)

Elements that are syntactically valid with a supported GUI tool are highlighted as blue and also have a hover message that describes both the corresponding CC3D component and currently detected downstream elements (automatically generated), 

![image](https://user-images.githubusercontent.com/21112182/89881560-a8fc3d80-db93-11ea-9b0f-e8b6d86c7f3e.png)

The context menu also displays the GUI tool of the currently selected XML element (if any) and a shortcut menu to all available GUI tools for quick addition/modification of plugins/steppables. Tools with XML elements that are already present in the code are detected and displayed with check marks, 

![image](https://user-images.githubusercontent.com/21112182/89881790-f8426e00-db93-11ea-8bb4-9f075356bfa9.png)

Selecting a GUI tool calls a GUI editor that either loads data from the XML (if present) or auto-populates fields from default data, 

![image](https://user-images.githubusercontent.com/21112182/89881961-27f17600-db94-11ea-901c-eddf110b6081.png)

Changing a cell type name has the downstream effect in Contact plugin, and so automatically calls the Contact GUI tool after making a change in the CellType GUI tool. The GUI tools are subclasses of a template, and new GUI tools can be added for plugins/steppables over time. 

Maybe we should we prioritize releasing this feature? I think that the code scanner might be too embedded to release it separately (can't remember off the top of my head), but this seems (to me) to be in a state where we can release it and add new GUI tools in future releases.

**Comment by jpsluka** [comment]
So where are these actually located? They have not been officially incorporated into the release version of CC3D.

**Comment by tjsego** [comment]
> So where are these actually located? They have not been officially incorporated into the release version of CC3D.

Right now, it's only available on the branch [features/contact_gui](https://github.com/CompuCell3D/CompuCell3D/tree/feature/contact_GUI) and not in the official distribution. The last we discussed it, the plan was to develop more GUI tools before an official release. I think that currently there are four or five available? The architecture works, and adding more GUI tools is a matter of individual GUI design and integration.

**Comment by jpsluka** [comment]
I think it would still be a good idea for Player/CC3D to do a quick XML validity check. It could also do other checks that people don't usually think of. For example, an XML file can have a duplicate tag, and unlike programming languages, XML parsers often use the FIRST occurrence of a tag and not the last.

   <Plugin Name="Volume">
      <VolumeEnergyParameters CellType="bcell" LambdaVolume="2.0" TargetVolume="50"/>
      <VolumeEnergyParameters CellType="bcell" LambdaVolume="2.0" TargetVolume="500"/>
   </Plugin>

Actually, I think it is unpredictable which tag it will use.

On online XML validator (https://www.w3schools.com/xml/xml_validator.asp) doesn't flag the above as invalid. (Though clearly it is not "well formed")

**Comment by jpsluka** [comment]
`   <Plugin Name="Volume">
      <VolumeEnergyParameters CellType="bcell" LambdaVolume="2.0" TargetVolume="50"/>
      <VolumeEnergyParameters CellType="bcell" LambdaVolume="2.0" TargetVolume="500"/>
   </Plugin>`

**Comment by tjsego** [comment]
> I think it would still be a good idea for Player/CC3D to do a quick XML validity check. It could also do other checks that people don't usually think of. For example, an XML file can have a duplicate tag, and unlike programming languages, XML parsers often use the FIRST occurrence of a tag and not the last.
> 
> ```
>    <Plugin Name="Volume">
> 
>       <VolumeEnergyParameters CellType="bcell" LambdaVolume="2.0" TargetVolume="50"/>
> 
>       <VolumeEnergyParameters CellType="bcell" LambdaVolume="2.0" TargetVolume="500"/>
> 
>    </Plugin>
> ```
> 
> Actually, I think it is unpredictable which tag it will use.
> 
> On online XML validator (https://www.w3schools.com/xml/xml_validator.asp) doesn't flag the above as invalid. (Though clearly it is not "well formed")

If we use the code scanner in the aforementioned branch, then we can tailor the errors/warnings at the level of CC3D and individual plugin/steppable.

**Comment by CompuCell3D** [comment]
TJ, and Jim you are giving great arguments in favor of ditching XML. I find it weird how we are doing the setup using XML . As you can see XML is a high maintenance language maybe we should ditch it and replace it with Python syntax? The only thing we would miss is CC3DML helper that comes handy but we could provide similar capabilities for Python syntax that would replace XML. Anyway, this is something to consider not a thing we have to act on right now

**Comment by tjsego** [comment]
I'm completely onboard with ditching the XML. The GUI tools in the aforementioned branch construct a simulation from a Python dictionary that gets passed around by the tools, and it's really easy to work with. We could declare a "simulation specification" dictionary that defines all simulation details, and the user could define a simulation in Python or with a new GUI that could replace current Wizard and be accessible during model specification. There is already a notion of this dictionary in the Wizard routines and code generators. We could also support specification in Python with similar code snippets to what we already have for CC3DML.

**Comment by CompuCell3D** [comment]
The issue is fixed. I will close discussion for now - can always reopen it
