### ISSUE TITLE
Refactor FPP plugin to include more flexible/convenient link definitions

### ISSUE THREAD

**Issue by CompuCell3D** [CompuCell3D/CompuCell3D#302]
We need much clearer explanations of how to create links and what they do. We should be able to define multiple classes of links and have clear ways of defining their energy functionals. At a minimum, we should be able to define a link type and then attach a link of a given type between any two cells. Having multiple links between the same cells with different energies is very powerful. Setting the parameters for individual links is currently confusing and needs to be better documented. 

I specifically want to be able to automatically generate links of the following type--nearest neighbors in a chain with target lengths equal to the current length. Second neighbor links in a chain with energies equal to arccos of (l-ltarget) or arcos^2 of (l-ltarget) to give bending moduli

**Comment by jpsluka** [comment]
We really need to describe the difference between links and FPP and ...

I would also add one more step beyond angles: dihedrals. (1-4 torsions instead of just 1-3 angles)

**Comment by tjsego** [comment]
Should be resolved by #361. Can we close this?

**Comment by tjsego** [comment]
Closing. We can open new issues that target specific aspects of the new interface.
