### ISSUE TITLE
CC3D hangs while running

### ISSUE THREAD

**Issue by nadaa** [CompuCell3D/CompuCell3D#31]
Hi,
I have noticed that sometimes cc3d simulation hangs after running, there is no error . It may work if I rerun it again!. What is the cause of this?

Thanks

**Comment by maciekswat** [comment]
can you send me the simulation you are trying to run? Not sure why this would happened and I cannot tell you without knowing more. Does it always do this or only with some type of simulations? If you can send me a simple simulation that shows this behavior I might be able to help

-- 
Maciej Swat

Biocomplexity Institute, Indiana University,

Simon Hall MSB1, 043D
212 S. Hawthorne Drive
Bloomington, IN  47405-7003

e-mail: mswat@indiana.edu
phone: (812) 855-2441
fax: (812) 855-5533

**Comment by nadaa** [comment]
Well, I used to call the simulation multiple times  from outside the player. I think this cause the problem.
Still, I couldn't figure out how to solve it!.
