### ISSUE TITLE
FPP links rendering

### ISSUE THREAD

**Issue by CompuCell3D** [CompuCell3D/CompuCell3D#312]
The links are NOT drawn properly if you chance the view to 3D or the plane of view (they are always rendered as if in x-y view no matter what)

**Comment by CompuCell3D** [comment]
Many people noticed odd behavior with FPP in CC3D during the class. FPP edges weren’t being displayed properly in player, the edges seem to come and go randomly and other odd behaviors.

 

I have a simulation now that appears to be changing the membership in the cell list by type data. For example;

 

        for cell1 in self.cell_list_by_type(self.ACELL):

            print("\t\t\t cell1.id,",cell1.id)

            for cell2 in self.cell_list_by_type(self.BCELL):

                d=cell_cell_dist(cell1,cell2)

                self.focalPointPlasticityPlugin.createFocalPointPlasticityLink(cell1, cell2, 10, d, 500)

                print("\t\t\t    cell2.id",cell2.id)

 

# calculate the distance between two cells, cell1 and cell2

def cell_cell_dist(cell1,cell2):

    import math

    d=math.sqrt((cell1.xCOM-cell2.xCOM)**2+(cell1.yCOM-cell2.yCOM)**2+(cell1.zCOM-cell2.zCOM)**2)

    return(d)

 

Gives as output:

 

                Len acell and bcell lists: 4 5

                  acell lists:

1 2 5 8

                  bcell lists:

3 4 6 7 9

                         cell1.id, 1

                            cell2.id 3

                            cell2.id 4

                            cell2.id 6

                            cell2.id 7

                            cell2.id 9

                         cell1.id, 3

                            cell2.id 3

                            cell2.id 4

                            cell2.id 6

                            cell2.id 7

                            cell2.id 9

                         cell1.id, 3

                            cell2.id 3

                            cell2.id 4

                            cell2.id 6

                            cell2.id 7

                            cell2.id 9

                         cell1.id, 4

                            cell2.id 3

                            cell2.id 4

                            cell2.id 6

                            cell2.id 7

                            cell2.id 9

                         cell1.id, 9

                            cell2.id 3

                            cell2.id 4

                            cell2.id 6

                            cell2.id 7

                            cell2.id 9

 

                Len acell and bcell lists: 4 5

                  acell lists:

1 2 5 8

                  bcell lists:

3 4 6 7 9

 

Notice the highlighted values are not cell.ids that are on the respective list and a value is repeated. The above behavior changes every run (even though I have an explicit seed set in the Potts section).

**Comment by CompuCell3D** [comment]
[FPP_test_Aug_2020b.zip](https://github.com/CompuCell3D/CompuCell3D/files/5053923/FPP_test_Aug_2020b.zip)

**Comment by jpsluka** [comment]
This might not be an FPP problem. It looks like CC3D doesn't properly process cell lists by type whe you embed them in cascade loops:  (pseudo code)
```
for cells of type a

   for cells of type b

       [gives a corrupted iteration list for the type a cells]
```

**Comment by maciekswat** [comment]
fixed
