### ISSUE TITLE
cell list iterates getting corrupted when they are nested

### ISSUE THREAD

**Issue by jpsluka** [CompuCell3D/CompuCell3D#316]
If you nest visit cells by type the outer cell list gets corrupted (but doesn't throw an error).

`    for cell_1 in self.cell_list_by_type(self.ACELL):

        for cell_2 in self.cell_list_by_type(self.BCELL):
`
The cell_1 list is corrupt in the above. The cell_1 list includes cells that are not of type ACELL.

Forcing the list to be enumerated up front fixes the bug;

`            for cell_1 in [cell for cell in self.cell_list_by_type(self.ACELL)]:

                for cell_2 in self.cell_list_by_type(self.BCELL):
`

This is a pretty serious bug and has no doubt confused a lot of people.

**Comment by tjsego** [comment]
We should do this conversion to iterators over Python lists in the steppable base class wherever necessary.

**Comment by CompuCell3D** [comment]
Fixed
