### ISSUE TITLE
Add logarithmic term to chemotaxis and document it

### ISSUE THREAD

**Issue by CompuCell3D** [CompuCell3D/CompuCell3D#338]
We really need to add the logarithmic chemotaxis to the XML and python
as a stadard function, so that lambda_chemo per cell =
lamda_chemo_reference/(K_chemo+value of field at COM , or avaeraged over
cell, etc,...) we need this one all the time so it should be a built in.

**Comment by jpsluka** [comment]
Yes! We also need to fix the current functions; they should be Hills function of the difference in concentration instead of the difference of the Hills' Function.

**Comment by JulianoGianlupi** [comment]
I believe those are in and it's a matter of documentation, see https://github.com/CompuCell3D/CompuCell3D/blob/master/CompuCell3D/core/CompuCell3D/plugins/Chemotaxis/ChemotaxisPlugin.cpp line 401 onward

**Comment by tjsego** [comment]
Resolved by #420. Closing.
