### ISSUE TITLE
Vecor field arrows dont appear to work in 3D

### ISSUE THREAD

**Issue by jpsluka** [CompuCell3D/CompuCell3D#340]
The demo Demos/ExtraFields shows cell level vector fields displayed. However, if the z dimension in the model is increased the arrows nor longer display. Player shows the field minimum at 1e299 and the maximum at NAN. 

In addition, there isn't any way to color cells in 3D except by cell type. Assigning a scalar field to the cells colors all cells the same even if their cell scale field value is different. The isosurface seem to work in 2D but don't do anything in 3D.

**Comment by CompuCell3D** [comment]
Good catch. Turns out CC3D uses "2D code" to init 3D actors

**Comment by maciekswat** [comment]
Fixed
