### ISSUE TITLE
Wildly different results with DiffusionSolverFE on Windows vs. Linux (Red Hat)

### ISSUE THREAD

**Issue by jpsluka** [CompuCell3D/CompuCell3D#341]
Running simulations that use DiffusionSolverFE on Windows and Linux (Red Hat) give wildly different results. Results are on the order of ten times larger field values in Linux vs. Windows. 

** Windows 10, CC3D version 4.2.3 20200815, launch from Twedit

** Linux Red hat (Tatooine), CC3D installed from CC3D_4.2.3_RedHat_7.5_64bit.tar.gz, run from command line using runScript.sh
(Tatooine's Red Hat is version 7.8)

Attached is a simple CC3D project that uses DiffusionSolverFE, runs for 10K mcs printing the min and max field values every 1000 mcs. Note that all the cells in the sim are frozen.

** Windows gives the exact same output every run (to 12 decimal places):
    ***********************mcs, field min and max: 9000 2.9675559997558594 46.45997619628906

** Linux gives slightly different output every run and **the values are 10x the Windows values** (output from 3 runs):
    ***********************mcs, field min and max: 9000 34.0976676940918  468.3082275390625
    ***********************mcs, field min and max: 9000 33.68669891357422 468.33697509765625
    ***********************mcs, field min and max: 9000 34.25188446044922 467.8564453125

I also notice some significant instabilities in the Linux version. The field values will oscillate up and down even though the field should be monotonically increasing (**all cells in the sim are fixed**).
[DS_DF_test.zip](https://github.com/CompuCell3D/CompuCell3D/files/5152953/DS_DF_test.zip)

**Comment by CompuCell3D** [comment]
Running the same simulation under Ubuntu 20.04 results in consistent values at the end of the simulation same values as on Windows

***********************mcs, field min and max: 9900 2.9675559997558594 46.45997619628906
Will check RH 8.0. My suspicion is that binaries for RH7.5 are simply bad

**Comment by CompuCell3D** [comment]
Results from OSX 10.14
	***********************mcs, field min and max: 9000 2.9675559997558594 46.45997619628906
Same as Windows and Ubuntu

**Comment by CompuCell3D** [comment]
RH 8.0
at 9000
***********************mcs, field min and max: 9000 2.9675559997558594 46.45997619628906
same as windows. 
RH7.5 when run on my Virtual box is consistent but gives different results from Window, ubuntu or OSX. I could investigate it further but I feel that at this point it might be wort doing native compilation of OSX on a target machine. In addition I can build new installation of RH under vmware player and see how this goes

**Comment by CompuCell3D** [comment]
Closing the issue - the binaries for RH 7.5 were messed up
