### ISSUE TITLE
NumberOfProcessors slows down runs on Red Hat Linux

### ISSUE THREAD

**Issue by jpsluka** [CompuCell3D/CompuCell3D#342]
Changing the NumberOfProcessors value in the Potts section of a model slows the run down on Red Hat Linux.

```
NumberOfProc      Run Time (sec)
   1                    44.56
   2                    69.38
   4                   319.16
```

** Linux Red Hat (Tatooine), CC3D installed from CC3D_4.2.3_RedHat_7.5_64bit.tar.gz, run from command line using runScript.sh

The simulation zip is attached.
[DS_DF_test.zip](https://github.com/CompuCell3D/CompuCell3D/files/5157182/DS_DF_test.zip)

(Tatooine's Red Hat is version 7.8)

**Comment by CompuCell3D** [comment]
This is to to be expected with the simulation that uses Secretion Plugin. Secretion should be specified in the DiffusionSolverFE directly. Specifying secretion in the separate secretion plugin actually slows down the simulation. this is documented in the CC3D manual

https://compucell3dreferencemanual.readthedocs.io/en/latest/plugins_section.html?highlight=secretion#secretion-plugin-legacy-version

The only reason to use Secretion plugin is when you want to have secretion by individual cells where actual secretion functions are called from Python. All other uses of Secretion plugin result in performance degradation

**Comment by jpsluka** [comment]
Then maybe we should add that to the comment in the new simulation wizard. "If DiffusionSolverFE is being used do not also use the Secretion plugin". It is not clear that the PDE code is also going to handle secretion by default. Or, add that as part of the comment in the XML and Python code inserted when the user selects the secretion option in the wizard.

**Comment by jpsluka** [comment]
Did some tests. 
Windows with secretion plugin:
1 cpu time 33.2 sec
4 cpu time 50.0 sec
Windows without secretion plugin:
1 cpu time 28.2 sec
4 cpu time 25.4 sec
So the secretion plugin does remove the extra cpu speed up but the effects is only a factor of 2x.

Red Hat with secretion plugin:
1 cpu 44.6 seconds
4 cpu 319.2 sec
Red hat without the secretion plugin:
1 cpu 36.3 sec
4 cpu 131.4 sec

So increasing the number of CPUs slows down Red Hat even without the secretion plugin.

This may be related to whatever the problem is with the DiffusionSolverFE on Red Hat, issue #341

**Comment by maciekswat** [comment]
RedHat 7.5 had serious issues - the gcc they distributed did not work with openMP directives. RH 8 or RH 6 was ok in this regard. I am closing this issue as this is related to one particular version of RH
