### ISSUE TITLE
Warning from runScript.sh on Linux

### ISSUE THREAD

**Issue by jpsluka** [CompuCell3D/CompuCell3D#343]
runScript.sh gives a warning (non fatal) on Linux systems (only system tried).

```
[jsluka@tatooine DS_DF_test]$ /home/jsluka/CC3D_423/CC3D_4.2.3_RedHat_7.5_64bit/runScript.sh    \
                   -i /home/jsluka/DS_DF_test/DS_DF_test/DS_DF_test.cc3d

runScript.sh: line 6: warning: setlocale: LC_NUMERIC: cannot change locale (C.UTF-8): No such file or directory
runScript.sh: line 6: warning: setlocale: LC_NUMERIC: cannot change locale (C.UTF-8)
```
If the behavior is expected we should add a message in the script saying so. This may also be a problem on Mac and Windows platforms though I did not check.

**Comment by CompuCell3D** [comment]
this is ok . Has no effect on the actual code. This command we are trying to add here was supposed to fix run script behavior when system language is different than English. It woudl be good indeed to fix it but not the highes

**Comment by jpsluka** [comment]
Perhaps just add a comment in the script files (for all three platforms) so that in the future, when people are debugging, they don't chase this non issue.

**Comment by jpsluka** [comment]
This REALLY needs to be fixed. If the CC3D runs fails for pretty much any reason this is often the ONLY error message supplied to the user. We need to quit making people chase tis non-existent problem.

**Comment by maciekswat** [comment]
fixed. New scripts do not have this warning
