### ISSUE TITLE
Remove self.stop_simulation() from all demos except demo of self.stop_simulation()

### ISSUE THREAD

**Issue by jpsluka** [CompuCell3D/CompuCell3D#366]
Three demos use code like:
        if mcs == 300:
            self.stop_simulation()
This should be removed. Only the one demo of the stop_simulation() function should actually use it. If the other demos need to only do a small number of MCS that should be defined in the normal way. I just had a user spend a couple hours trying to figure out why the maximum number of MCS in the Potts block was being ignored in a demo.

These two demos use stop_simulation():
bacterium_macrophage_new_style\Simulation\bacterium_macrophage_2D_steppables.py      
cellsort_project_py_step_new_style\Simulation\cellsort_2D_steppables.py

**Comment by tjsego** [comment]
See #450. The calls are intentional based on the purpose of those steppables. If there's a request to modify the purpose of either steppable, it can be raised in a new issue. Closing.
