### ISSUE TITLE
Player assumes cell type id

### ISSUE THREAD

**Issue by jpsluka** [CompuCell3D/CompuCell3D#367]
If a simulation skips a cell type id in the CellType plugin, then player gets confused about the cell id to type names and color mappings. For example:
```
   <Plugin Name="CellType">
      <!-- Listing all cell types in the simulation -->
      <CellType TypeId="0" TypeName="Medium"/>
      <CellType TypeId="1" TypeName="Fibroblast"/>
      <CellType TypeId="3" TypeName="IC"/>
   </Plugin>
```
Note no TypeID="2" in the above.

In player, the preferences windows shows:
![settings_bug](https://user-images.githubusercontent.com/22944062/97635747-3b331580-1a0e-11eb-89c5-2b1c245afc63.png)

The "IC" cell type is shown as TypeID 2 instead of 3.

When the sim is run the cells are colored for the correct number

![settings_bug2](https://user-images.githubusercontent.com/22944062/97635762-42f2ba00-1a0e-11eb-959a-5a1f30fe4350.png)

Note that the IC cells are purple, which is correct in the settings for type 3, not red like the settings window says.

**Comment by jpsluka** [comment]
If a simulation skips a cell id in the CellType plugin, thebn player gets confused about the cell id to type names and color mappings. For example:
   <Plugin Name="CellType">
      
      <CellType TypeId="0" TypeName="Medium"/>
      <CellType TypeId="1" TypeName="Fibroblast"/>
      <CellType TypeId="3" TypeName="IC"/>
   </Plugin>
Note no TypeID="2" in the above.

In player, the preferences windows shows:
![settings_bug](https://user-images.githubusercontent.com/22944062/97635261-69642580-1a0d-11eb-97ce-06730656c098.png)

The "IC" cell type is shown as TypeID 2 instead of 3. 

When the sim is run the cells are colored for the correct number
![settings_bug2](https://user-images.githubusercontent.com/22944062/97635376-a6301c80-1a0d-11eb-82d5-eaa6d494d391.png)
Note that the LC cells are purple, which is correct in the settings for type 3, not red like the settings window says.

**Comment by CompuCell3D** [comment]
interesting. Definitely worth fixing. On that note, I wonder if it would be a good idea to stop using type_ids and have them automatically assigned and then force users to use syntax like `cell.CONDENSING` ? So if a user uses type_ids in CellType plugin we keep current behavior but if user decides to skip type_id we assign it automatically. Obviously we would have to check if users do not mix coding styles. but I am trying to thikng about ways to simplify our simulation descriptions. There are pleny of opportunities for improvements. @tjsego I am sure you have many similar thoughts

**Comment by tjsego** [comment]
I prefer using automatic assignment.

**Comment by tjsego** [comment]
Probably the best way to address this while maintaining backward compatibility is to make specification of a type ID optional and automatically populated when not specified. That way nothing written is broken, but we can encourage implicit ID specification going forward.

**Comment by tjsego** [comment]
Accomplished in [feature/impl_type_id](https://github.com/CompuCell3D/CompuCell3D/tree/feature/impl_type_id). Holding off on the PR until after the upcoming release.

**Comment by tjsego** [comment]
Done in #455. Closing.
