### ISSUE TITLE
Simulation-Function?

### ISSUE THREAD

**Issue by MasterKarinski** [CompuCell3D/CompuCell3D#37]
Hi,
it's me again...
I'm trying to optimize some simulations for getting better and better fitness results. I tried to use the Parameter Scan function but it's just a parameter-listing I cannot use efficiently for my optimization tool. Is there a better solution, for example some kind of fitness- or objective function/mathematical model the simulations uses? Is it possible to extract it from code? Maybe after initializing a simulation?

Sincerely,
Karinski

**Comment by maciekswat** [comment]
Great question. We were thinking about implementing it and actually 
there is a chance that we might have someone to work on this However at 
the moment you are pretty much on your own... Yes, Paramater Scan will 
do naive grid search it does not do optimization


However, I am thinking that if you can save state of the simulation (and 
CC3D allows this) you may write your own optimization code. I would be 
happy to help you with this - it could be instructive for us to try it 
first on a real problem before including optimization code in the code 
code base.


Why don't you give me a better description of what you are doing and 
what you are trying to optimize. Ideally if I could see a toy version of 
your model that woudl help me. And perhaps we can take this discussion 
offline so please feel free to email me directly

M

**Comment by tjsego** [comment]
See [chemotaxis_calibrate.py](https://github.com/CompuCell3D/CompuCell3D/blob/master/CompuCell3D/core/Demos/CallableCC3D/ChemotaxisCalibrateDemo/chemotaxis_calibrate.py). @CompuCell3D can we close this?
