### ISSUE TITLE
Cryptic error message when trying to rerun a previously failed parameter scan

### ISSUE THREAD

**Issue by jpsluka** [CompuCell3D/CompuCell3D#371]
If a parameter scan fails at initial launch the output directory is created. On subsequent attempts to run the parameter scan, CC3D sees the output folder exists and then expects that the status file (param_scan_status.json) exists and that the parameter scan is supposed to continue. If the previous run had failed, then that output file does not exists and the error message complains about the missing json file instead of suggesting that the output folder needs to be completely deleted, or actively correcting the problem by just creating a new json file like it would the first time the scan is run.

**Comment by c67f** [comment]
I think I'm also having this problem, or at least a similar one. I'm trying to run a simulation with a parameter scan, but pressing run does nothing in the player, and the terminal says "No such file or directory: [file path]\param_scan_status.json". Changing the file path hasn't worked for me, and I'm not sure how to reset the parameter scan in 4.2.4 (if that would even solve this).

**Comment by jpsluka** [comment]
What CC3D version are you using?

For the most recent CC3D (4.2.3 20200821), I believe you should launch the run from Twedit++. That  should open a dialog that asks a few questions.
![image](https://user-images.githubusercontent.com/22944062/100676542-1ac0e880-3337-11eb-963c-ec9862e3bdec.png)
You can either click on the "Run" button or click the "Display Command Line" and copy that command to a command window and run it that way,

If you are not getting that dialog then check the files. The file "ParameterScanSpecs.json" should be in the Simulation folder and your project's .cc3d file should have a line pointing to it like:
 <ParameterScan Type="ParameterScan">Simulation/ParameterScanSpecs.json</ParameterScan>

To reset a run I believe you can just delete the output folder like:
C:\Users\USERNAME\CC3DWorkspace\SOMEJOBNAMEParameterScan
(where USERNAME is you, and SOMEJOBNAME is the root name of your project)

**Comment by c67f** [comment]
I have been getting that dialog, but still having the problem. Deleting the output file didn't seem to help.

**Comment by c67f** [comment]
I just checked and I didn't see the parameter scan line when I opened up the .cc3d file, but adding it in didn't seem to help.

**Comment by jpsluka** [comment]
If you don't mind sharing, can you zip the project and send it to me at jsluka@iu.edu?

**Comment by c67f** [comment]
Sorry for the late response-I wasn't sure if my job would let me share the project, but I can. I've sent the zip to the provided. email address. Thanks for the help!

**Comment by maciekswat** [comment]
Since parameter scans have been reimplemented and are handled differently in the recent versions I am closing this ticket
