### ISSUE TITLE
Re-starting simulation that results depend on MCS

### ISSUE THREAD

**Issue by aopisco** [CompuCell3D/CompuCell3D#39]
Hi,
I'm doing tissue modelling and I'd like to be able to re-start the simulation from a previous configuration to try different treatments but because my steppables depend on the MCS I'm not succeeding. Any suggestions on how to setup the MCS to the one at which the configuration was saved? Thanks a lot, Angela

**Comment by maciekswat** [comment]
Could you email me a demo/toy version of your simulation so that I could see what exactly depends on MCS?  The way restart files work is that once CC3D saves the snapshot it also saves MCS and during restart MCS is set to the value that was saved together with the complete simulation snapshot

**Comment by maciekswat** [comment]
you can email me directly - this works best

**Comment by aopisco** [comment]
hi, just did, please let me know if you got it, thanks!

**Comment by maciekswat** [comment]
Closing - an old issue that likely has been already fixed. If not we need to reopen new ticket and move it to the top of the stack
