### ISSUE TITLE
Cell types invisible in 3D should  not be inherited acorss simulations

### ISSUE THREAD

**Issue by jpsluka** [CompuCell3D/CompuCell3D#394]
When a new simulation is created it should not inherit the list of cells types invisible in 3D from previous simulations. The new simulation should always have just cell type 0 listed as invisible in 3D.

**Comment by CompuCell3D** [comment]
Closing the issue the PR that has been merged implements the fix. If you @jpsluka  find that something is out of order, just reopen issue or make a new one
