### ISSUE TITLE
mapping timesteps to real time

### ISSUE THREAD

**Issue by nadaa** [CompuCell3D/CompuCell3D#40]
Hi,

How can I convert real time to cc3d time steps?

Thanks

**Comment by maciekswat** [comment]
I guess it is up to you what the conversion factor is. Typically you 
look at the cell diffusion coeeficient and compare it to experimental 
time lapse images and from there you deduce the time scale


Take a look at those two links they will give you an outline of the 
procedure you typically follow to establish connection between MCS and 
physical time

http://journals.plos.org/plosone/article?id=10.1371/journal.pone.0127972

http://www.compucell3d.org/Workshops/Workshop11/Materials/AbbasHowTo


let me know if this is helpful


M
