### ISSUE TITLE
Problem in runing a model

### ISSUE THREAD

**Issue by nadaa** [CompuCell3D/CompuCell3D#42]
Dear Mr. Maciekswat,
I want to run a model published in  https://www.ncbi.nlm.nih.gov/pubmed/22461894
I got the following image after I run it:
![screenshot from 2017-03-22 11-43-33](https://cloud.githubusercontent.com/assets/1457075/24222102/2c5eaa92-0f0e-11e7-89b3-52d8113f309e.png)

Is there any configuration to change before running it?

Thanks,
Nada

**Comment by maciekswat** [comment]
how did you install CC3D? From source? If so I am not sure if in the 
latest versions we supply BionetSolver. We depreciated this library and 
replaced it with a much better one SBMLSolver So in principle the best 
strategy going forward would be to take the model that uses BionetSolver 
and recode all reaction-kinetics ODEs using SBML solver. Here is a brief 
tutorial of how to use SBML solver:

http://www.compucell3d.org/BinDoc/cc3d_binaries/Manuals/PythonScriptingManual_v.3.7.5.pdf

page 54-63. Let me know if this helps

**Comment by maciekswat** [comment]
@nadaa . can we close this thread?
