### ISSUE TITLE
VTK files not being saved

### ISSUE THREAD

**Issue by dza6549** [CompuCell3D/CompuCell3D#43]
Hi

I'm running CompuCell3D 3.75 Rev: 20170130 on Windows 7. Standard install to C:\CompuCell3D-64bit
Followed tutorial https://www.youtube.com/watch?v=cEE6IeaQRwU I am using the Angiogenesis.cc3d file and am trying to output 3D VTK to be rendered in Blender 3D.

However no output folder is being created or VTK files outputted.

Please let me know what steps to take to diagnose and remedy.  I can't see anything abnormal in the command window. There appears to be no evidence in the command window of lattice files being written out.

Thanks

D

**Comment by maciekswat** [comment]
Hi  

Did you check “Save lattice every Nth MCS” in the Configuration dialog on the “Output” tab?

Or are you running CC3D from command line? Typically those files are written to <your home dir>/CC3DWorkspace.

Look for folder with recent timestamp. Let me know if this works

**Comment by maciekswat** [comment]
@dza6549 : can we close this thread?

**Comment by dza6549** [comment]
Sure. Thanks for asking.
