### ISSUE TITLE
move_cell doesn't work correctly

### ISSUE THREAD

**Issue by jpsluka** [CompuCell3D/CompuCell3D#441]
move_cell doesn't work correctly. If the cell is displaced by less than the cell's width than any pixels that were common to both cell locations are set to medium.  Looks like the code is moving the cell to the new location then deleting all pixels from the original location (or setting them to medium) evn if those pixels are part of the cell in its new location.

Also, move_cell requires the PixelTracker plugin but that is not in the manual or in the code snippet that Twedit++ inserts.

Found on WIndows 10, CC3D 4.2.4 20210123

**Comment by JulianoGianlupi** [comment]
PR #442 should make movement safe (don't delete old that are part of new) and adds to the snippet that pixel tracker is required

**Comment by JulianoGianlupi** [comment]
#445 closes this issue
