### ISSUE TITLE
Linker Error while building from source

### ISSUE THREAD

**Issue by dengeltheyounger** [CompuCell3D/CompuCell3D#454]
I am running Manjaro with GCC 10. I am consistently running into a linker error, "multiple definition of allocatedUnitNumber". Looking at the source code, it looks like the variable is defined a single time in a header file, and then used extern in other header files. As far as I know, GCC has changed how it handles functions (generally, it is best to define the variable in the c file and then extern in the h file). However, altering the source code did not solve that problem. In addition, I tried to modify the cmake file in order to add "-fcommon" as a compiler option. That also did not solve the problem.

Edit: I managed to solve the linker error, but only by literally commenting out every single line that declared or defined that variable. I have no clue how that works, but now the source code is happily compiling away.

This is the result of running make:
[error.txt](https://github.com/CompuCell3D/CompuCell3D/files/6643176/error.txt)

**Comment by CompuCell3D** [comment]
can we close this issue for now? I dont think we have tried compiling CC3D with GCC 10+ but it looks like there might be some work to be done
