### ISSUE TITLE
new release not opening player

### ISSUE THREAD

**Issue by aopisco** [CompuCell3D/CompuCell3D#46]
![screen shot 2017-06-29 at 18 43 35](https://user-images.githubusercontent.com/25906087/27702521-3d6c55f0-5cfc-11e7-9510-e481f67e730f.png)

I've tried loading a couple of simulations including demos but I can't open player
I'm using Mac OS El Capitan 10.11.6

**Comment by CompuCell3D** [comment]
Indeed this is a bug but here is a temporary solution:
go to `<YOUR HOME DIRECTORY>/.compucell3d/_settings.xml` and find line with `UseInternalConsole`. It should look a s follows:

`<e Name="UseInternalConsole" Type="bool">False</e>`

Change it to:

`<e Name="UseInternalConsole" Type="bool">True</e>`

we will fix this bug in the upcoming update, Please confirm if the proposed solution works
