### ISSUE TITLE
Getting the following error when trying to compile

### ISSUE THREAD

**Issue by supunkamburugamuve** [CompuCell3D/CompuCell3D#464]
Envrionment - Ubuntu 20.04

In file included from /home/supun/anaconda3/envs/cc3d_2020/include/vtk-8.2/vtkAtomicTypes.h:18,
                 from /home/supun/anaconda3/envs/cc3d_2020/include/vtk-8.2/vtkObjectBase.h:54,
                 from /home/supun/anaconda3/envs/cc3d_2020/include/vtk-8.2/vtkObject.h:45,
                 from /home/supun/anaconda3/envs/cc3d_2020/include/vtk-8.2/vtkAbstractArray.h:61,
                 from /home/supun/anaconda3/envs/cc3d_2020/include/vtk-8.2/vtkDataArray.h:39,
                 from /home/supun/anaconda3/envs/cc3d_2020/include/vtk-8.2/vtkIntArray.h:32,
                 from /home/supun/projects/nanobio/CC3D_PY3_GIT/CompuCell3D/CompuCell3D/core/pyinterface/PlayerPythonNew/FieldExtractor.cpp:10:
/home/supun/anaconda3/envs/cc3d_2020/include/vtk-8.2/vtkAtomic.h:28:10: fatal error: tbb/atomic.h: No such file or directory
   28 | #include <tbb/atomic.h>
      |          ^~~~~~~~~~~~~~
compilation terminated.

**Comment by supunkamburugamuve** [comment]
I was using this guide

https://compucell3d.org/SrcBin/CC3D_4xx_linux_compile_conda_based

**Comment by tjsego** [comment]
@supunkamburugamuve did you include the tbb package on the CC3D conda channel? The command is `conda install -c compucell3d tbb_full_dev`.

**Comment by supunkamburugamuve** [comment]
yes, it was the issue. it built successfully
