### ISSUE TITLE
Validate simulation name in Wizard

### ISSUE THREAD

**Issue by tjsego** [CompuCell3D/CompuCell3D#465]
Certain characters in a simulation name can cause errors. These error-causing characters should be reported during simulation construction.

**Comment by CompuCell3D** [comment]
@tjsego  Do we know what names are problematic?

**Comment by tjsego** [comment]
> @tjsego Do we know what names are problematic?

The generated steppable is given a name according to the simulation name, so anything that would generate an invalid python class name. No spaces, no starting with a number, etc. In the very least, we could use `isidentifier` and reject names that return `False`.

**Comment by CompuCell3D** [comment]
Looks like the issue is fixed
