### ISSUE TITLE
CompuCell3D Screen Saves Don't Match Settings

### ISSUE THREAD

**Issue by dengeltheyounger** [CompuCell3D/CompuCell3D#469]
So, I've configured CompuCell3D so that the heatmap legend is shown (on the left side), the heatmap's max and min at that MCS is shown (on the bottom), and that the heatmap's max and min are not fixed. I've noticed that when I check the "save image every [number] mcs" in the configuration settings, the output images only give the heatmap's max and min at the bottom. The heatmap's legend is between min and 1, not between min and max. Because the heatmap is capped between min and 1, the output images wind up showing one gigantic red blob that doesn't really tell you anything about the state of the region at that MCS. I'm currently using 4.2.4. I'm going to try updating to 4.2.5 and see if that fixes the problem (although 4.2.5 includes its own bugs and incompatibilities that I wanted to avoid that) if possible.

Is there some way to indicate to CompuCell3D that I want it to output exactly what it actually displays in the simulation? It is very strange to configure it, and then to discover that it only partially applies those configurations in the output images (despite the simulation images showing exactly what I asked for).

**Comment by CompuCell3D** [comment]
CC3D should honor the layout of the graphics widget from the time you press "camera" button. Now, I have not checked if it handles location of legend properly. we can certainly do it and if there is a problem we will fix it

**Comment by CompuCell3D** [comment]
I checked 4.2.5 and it behaves correctly I believe - when you click camera button to instruct it to start taking screenshot it will use windows concentration view window settings from the time during which you clicked camera button. Now, when you change the settings in the GUI later the screenshots will still be taken with the settings that existed when you clicked camera button . If you would like to change those screenshot settings you would need to (in 4.2.5) remove <your_simulation_folder>\screenshot_data\ folder and generate screenshot_data folder by clicking camera button - which essentially means that you manually remove old screenshot connfiguration and create new one. It is a bit inconvenient and we will fix it in future releases but at lease this should give you correct behavior in 4.2.5. Please let us know if this solution works for you

**Comment by jpsluka** [comment]
In other words, "no", it does not behave correctly. It behaves consistently and in a manner that is not clear to the user.

**Comment by dengeltheyounger** [comment]
That's very strange. Pressing the camera button does not lead it to respect the settings that I enable, and changing to 4.2.5 does not seem to make a difference. The field and cell images made by the simulation will have the correct min and max (which are local to the MCS), and the legend will reflect this. However, the output images that are saved in CC3DWorkspace/ do not. The only thing that I have not tried is removing screenshot_data and regenerating. It could be that is what needs to be done. I'll check it out tomorrow.

**Comment by dengeltheyounger** [comment]
It looks like it was removing the screenshot_data folder that did it. Thanks for mentioning that! The only thing is that I would recommend having the changes be applied immediately after closing settings (which includes replacing screenshots.json and "pressing" the camera button) instead of doing the extra two manual steps. I may open a separate request for that if it hasn't already.
