### ISSUE TITLE
Corrected paths are not properly handled during unzipping

### ISSUE THREAD

**Issue by tjsego** [CompuCell3D/CompuCell3D#473]
When unzipping to a non-unique location, an error is generated reporting that a .cc3d file cannot be located. 

My guess is, the corrected location (to a unique location) is not being used when searching for the .cc3d file.

**Comment by CompuCell3D** [comment]
I wonder if this happens when the project is zipped  using Twedit++ or if it is zipped using external tool that creates a different layout (in which case I saw that happen). It would be good to get an example of zipped project that has this issue

**Comment by CompuCell3D** [comment]
Fixes merged

**Comment by CompuCell3D** [comment]
Fixes merged
