### ISSUE TITLE
SteadyStateDiffusionSolver can't edit the field in 3D excep at z=0

### ISSUE THREAD

**Issue by jpsluka** [CompuCell3D/CompuCell3D#476]
SteadyStateDiffusionSolver documentation says you can poke values into a SteadyStateDiffusionSolver field, e.g., field[x,y,z]=value. This appears to only work if z=0 (as if the field is being treated as 2D and not 3D like SteadyStateDiffusionSolver is supposed to be)
[SteadyStateDiffusionSolver.zip](https://github.com/CompuCell3D/CompuCell3D/files/6949599/SteadyStateDiffusionSolver.zip)

**Comment by CompuCell3D** [comment]
fixes merged
