### ISSUE TITLE
Player gets confused on if the console should be displayed

### ISSUE THREAD

**Issue by jpsluka** [CompuCell3D/CompuCell3D#478]
(Noticed on Windows, haven't checked other platforms)
The [View][Console] option does not show the correct state when Player is started. Whether or not the console is shown has no relationship to if [View][Console] is checked or not. Typically it is unchecked but the console is still shown. Clicking then unclicking the menu gets the menu display to match the state of the console window. In the screen shot below, note that the console option is unchecked but the console is still being shown. This is the state that Player often opens in.

![Untitled](https://user-images.githubusercontent.com/22944062/128611272-1a6be972-4cb7-4564-b89f-0105807ca2ef.png)

**Comment by CompuCell3D** [comment]
fixes merged
