### ISSUE TITLE
MacOS First-time installation: "Unidentified developer" 

### ISSUE THREAD

**Issue by Milotrince** [CompuCell3D/CompuCell3D#510]
OSX 11.5.2 (Big Sur)

> Note: .dmg installer does not work as expected
<img width="1487" alt="Result from .dmg installer" src="https://user-images.githubusercontent.com/19580648/142482432-f67e1ace-b7f1-494c-8c00-910ff0f24099.png">

Steps:
- Download CC3D 4.2.5 **.zip** file: https://versaweb.dl.sourceforge.net/project/cc3d/4.2.5/mac/OSX_10.9-10.13/CC3D_4.2.5_20210828.zip
- Try executing any of the `.command` files
- Allow unidentified developer in System Preferences > Security & Privacy
- Still unable to open 

Something that didn't work: `xattr -d com.apple.quarantine FILENAME`
Temporary fix: `sudo spctl --master-disable`

**Comment by CompuCell3D** [comment]
This is to be expected. For Big Sur you should use https://sourceforge.net/projects/cc3d/files/4.2.5/mac/OSX_10.14%2B/cc3d_4.2.5_OSX_10.14%2B.dmg/. Try and see if this works for you. The zip file is for older OSX machines

**Comment by CompuCell3D** [comment]
I am closing this issue because wrong installer was used so really it was not the problems.
