### ISSUE TITLE
Saving plot data requreis full path

### ISSUE THREAD

**Issue by jpsluka** [CompuCell3D/CompuCell3D#514]
Saving plot data (on windows) requires a full path. Without the path the file doesn't appear to be written.

            self.plot_win.save_plot_as_png( "C:\\Users\\jsluk\\Desktop\\plot_screen_shot_.png")
            self.plot_win.save_plot_as_data("C:\\Users\\jsluk\\Desktop\\plot_data.txt")

The Twedit++ helper code should insert, e.g.,

            # here we specify size of the image saved (1000x1000) - default is 400 x 400
            # resizing of the image is not guaranteed to be implemented
            self.plot_win.save_plot_as_png("file_name_with_full_path", 1000, 1000)

for both **self.plot_win.save_plot_as_png** and **self.plot_win.save_plot_as_data**

**Comment by CompuCell3D** [comment]
Fixed. In previous versions the plots were saved into the directory where CC3D was installed - not the best option
