### ISSUE TITLE
Nice if self.open_file_in_simulation_output_folder passed through other file open options

### ISSUE THREAD

**Issue by jpsluka** [CompuCell3D/CompuCell3D#516]
It would be nice if self.open_file_in_simulation_output_folder passed through other python file open options like;
      self.open_file_in_simulation_output_folder("MyFileName.csv", mode='a'**,  newline=''"**)
instead of just the file name and file mode.

**Comment by CompuCell3D** [comment]
Fixed . now there is additional option to use `with` statement to manage files. For example:
`        with self.open_in_output_dir('my_files/demo.txt', mode='w') as (fh, out_path):
            fh.write('hello')`

**Comment by jpsluka** [comment]
Will this allow passing other file open arguments such as buffer length? In python you can
`open('my_file', 'r+', 128)`
which set the buffer size to 128 chars, or
`open('my_file', 'r+', 1)`
which set buffering to lines

**Comment by CompuCell3D** [comment]
for now you have to use argument names e.g. `self.open_file_in_simulation_output_folder("MyFileName.csv", mode='a', newline='\n', closefd=True)` etc. so while positional arguments might not work the keyword arguments will.
