### ISSUE TITLE
Manual section on RandomSeed incorrect

### ISSUE THREAD

**Issue by jpsluka** [CompuCell3D/CompuCell3D#521]
https://compucell3dreferencemanual.readthedocs.io/en/latest/potts_and_lattice.html?highlight=randomseed#potts-section

The section on RandomSeed is wrong. It says if you do not use the RandomSeed then all runs are the same. 

_**RandomSeed** is used to initialize random number generator. If you do not do this all simulations will use same sequence of random numbers. Something you may want to avoid in the real simulations but is very useful while debugging your models._

Should be something like
_**RandomSeed** is used to initialize random number generator. If you do not do this then the seed is picked randomly and all runs will be different. For debugging purposes (and in some cases for parameter scans and other  optimization tasks) it is useful to generate the same set of random numbers across multiple runs. To do this, include the **RandomSeed** XML tag with an integer value._ 

` <RandomSeed>167473</RandomSeed>`

_All simulations with the same CompuCell3D code and the same seed will use the same sequence of random numbers and produce the same results.  Note that if you are also using the Python random number generator (e.g., you have "import random" in your python code) then you may need to explicitly set the seed for that as well. For example;_
```
import random
random.seed(1234)
```

**Comment by CompuCell3D** [comment]
yes we will fix it

**Comment by jpsluka** [comment]
I updated the text for RandomSeed in the .rst file.

**Comment by CompuCell3D** [comment]
Thanks Jim. Closing the ticket
