### ISSUE TITLE
Default color bar ranges for field displays in Player

### ISSUE THREAD

**Issue by jpsluka** [CompuCell3D/CompuCell3D#526]
In Player, the default ranges for field display should be minimum fixed at zero and maximum floating. The current default is minimum floating and maximum fixed at 1
![Untitled](https://user-images.githubusercontent.com/22944062/161157151-0b4141d1-f141-4e3d-bcfa-5b1659dfd1c2.png)
.

**Comment by CompuCell3D** [comment]
Should be fixed now
