### ISSUE TITLE
Player can't color >10 cell types

### ISSUE THREAD

**Issue by JulianoGianlupi** [CompuCell3D/CompuCell3D#529]
Copied from https://www.reddit.com/r/CompuCell3D/comments/u2dlrn/increase_the_number_of_cell_types/

Hi there,

I have programmed 64 cell types into the model. However, after the first 10 cell types, they all display the same color as the 10th. In the cell color section, they all appear black as shown below. When I try to add a cell type in the configuration settings, the player crashes. I am using 4.2.5 on linux.

Cheers.

![image](https://user-images.githubusercontent.com/35964356/163210520-3f33e6c4-2bbf-4e1b-86b9-115b91bee29b.png)

**Comment by jpsluka** [comment]
I checked this on Windows 10 for 4.2.5 and 4.3.0 and the problem exists there as well.

The player window lists all the cell types (all 20), but only the first ten have a color, the rest are black.
All cell type id's beyond ten get the color assigned to ten in the cell field window
Player knows about the cell types and they can be accessed, counted, etc.

CC3D preferences menu only show the first ten types on the Cells/Colors tab
Clicking the "add" button crashes.
*** There really shouldn't be an "add button" on this menu anyway. *** 
Users really shouldn't be able to add a cell type in Player.

**Comment by CompuCell3D** [comment]
should be fixed in latest source code snapshot

**Comment by jpsluka** [comment]
Still need to remove the "add" button from the colors menu in Settings in Player, and the "-" button next to it as well.

**Comment by CompuCell3D** [comment]
Fixed
