### ISSUE TITLE
Enhancement: Ability to have python stop a simulaation running in player and wit for the resume button

### ISSUE THREAD

**Issue by jpsluka** [CompuCell3D/CompuCell3D#532]
It would be nice to be able to pause a simulation running in Player at a particular MCS. Basically allow python to press Player's "Step" or "Pause" button. Then have the sim resume when the user presses Player's "Run" button.

**Comment by CompuCell3D** [comment]
fixed

**Comment by CompuCell3D** [comment]
Done

**Comment by maciekswat** [comment]
@jpsluka can we close this issue or do we need some functionality to be added? If so can you reopen a new issue s that it is at the top of the stack

**Comment by jpsluka** [comment]
We can close this one, though the original request was not addressed. 
We can now pause player with an option in player.
What I wanted was the ability to pause player using a command in a python steppable.

**Comment by maciekswat** [comment]
ok I will open new issue to address this request

**Comment by jpsluka** [comment]
I tried some tests using the Python debugger (PDB). It looks like you can set a break using PDB that will pause a simulation running in Player, then you can check values and do the other debugger type actions. The simulation can then be resumed (perhaps running until the next preset debugger break).

breakpoint() is a native function in Python 3.7 so no imports are necessary. The user can do something like:
```
if mcs == 1000:
    breakpoint()
```

Can then examine variables etc. and typing 'c' on the console continues the simulation.

**Comment by jpsluka** [comment]
https://docs.python.org/3/library/pdb.html

**Comment by maciekswat** [comment]
Nice fix, but I will add `self.pause()` function to the steppables
