### ISSUE TITLE
Parameter sweep fails for CC3D 4.3.0

### ISSUE THREAD

**Issue by jpsluka** [CompuCell3D/CompuCell3D#535]
Observed on Windows 10, CC3D 4.3.0 rev. 2

Parameter sweeps fails since the environment variable PREFIX_CC3D is not defined. Attached is the parameter sweep dialog for 4.3.0 and 4.2.5 (which still works)'
![screenshots](https://user-images.githubusercontent.com/22944062/166338514-bc01f59e-3134-44e6-9d0f-ba475fa2971d.png)

**Comment by CompuCell3D** [comment]
Looks like it is fixed. Closing the issue
