### ISSUE TITLE
Running cc3d 4.3.0 headless through external python scripts crashes with fpp links

### ISSUE THREAD

**Issue by tc2fh** [CompuCell3D/CompuCell3D#536]
Simulation runs fine through player however throws an error shortly after step 0 while running a simulation with FPP links.

Here is the error:
![image](https://user-images.githubusercontent.com/88403622/167647501-7b891d8e-a41b-4320-91bd-fbeee2f8fdb2.png)

I am running cc3d 4.3.0 on Windows 11 installed through conda forge into a conda environment.

**Comment by CompuCell3D** [comment]
Does it happen only with FPP ;links (in the headless mode)?

**Comment by CompuCell3D** [comment]
should be fixed in the latest code snapshot

**Comment by CompuCell3D** [comment]
Looks like the issue is fixed
