### ISSUE TITLE
Clicking anywhere in Player's sub-window with the cell type map crashes player

### ISSUE THREAD

**Issue by jpsluka** [CompuCell3D/CompuCell3D#537]
In a 2D model, if you click anywhere in the bottom part of the cell type key window, where the 'Show in 3D' boxes are, crashes player. The error message is;

```
Traceback (most recent call last):
  File "C:\CompuCell3D\Miniconda3\lib\site-packages\cc3d\player5\UI\CellTypeColorMapView.py", line 66, in mouseReleaseEvent
    if index.column() == model.show_in_3d_idx:
AttributeError: 'NoneType' object has no attribute 'show_in_3d_idx'
```
![Untitled](https://user-images.githubusercontent.com/22944062/168633922-203c2bf7-d3a5-4b04-ba39-e87dc336dd94.png)

Windows 10, CC3D version 4.3.0v2

**Comment by CompuCell3D** [comment]
Fixed

**Comment by CompuCell3D** [comment]
Fixed
