### ISSUE TITLE
Conflict between conda installations

### ISSUE THREAD

**Issue by tjsego** [CompuCell3D/CompuCell3D#546]
On Windows at least, the current distribution method causes a conflict with system installations of conda that breaks some functionality from the installer package. I'm seeing the following issue, 

* The generated ``conda-shell.bat`` activates the base environment of the system installation of conda, and not the environment installed by the installer when using ``call``. 
* Additionally (not sure if related), the Windows installer sometimes fails to install the ``compucell3d`` conda package, reporting a conflict in python version. When manually activating the conda environment and installing the package, I see no issues.

**Comment by CompuCell3D** [comment]
I think recent changes to run scripts (https://github.com/CompuCell3D/cc3d_build_scripts/commit/54fabdc84977285eb150778cb64ef713e7ccaae4) and fixes to the installer address the problem. Closing the issue. Can reopen if necessary
