### ISSUE TITLE
Multiple processors does not work on Windows 10 and poorly on Ubuntu

### ISSUE THREAD

**Issue by jpsluka** [CompuCell3D/CompuCell3D#555]
Using multiprocessors on Windows 10, CC3D 4.3.0 and 4.2.5 uses more CPU but does actually make the run any faster.
[DynamicNumberOfProcessors.zip](https://github.com/CompuCell3D/CompuCell3D/files/8970768/DynamicNumberOfProcessors.zip)

Attached is an edited version of the the named demo. This version does not change the number of processors during the run or resize the lattice like the original demo does. Instead it generates its own wall clock time for the run and prints it at the end. My Windows 10 laptop has 4 cores and 8 logical processors.

`Processors,      Windows CPU load,   CC3D time (sec),    wall clock (sec)

    1                            17%                         67                       66

    2                            58%                         56                       56

    4                            75%                         62                       62

    6                            75%                         56                       56`

So the CPU load increases but the actual wall-clock time does not change as you increase the number of processors. 

The simulation is not saving screenshots and the debug frequency was 100.

**Comment by jpsluka** [comment]
I've run tests on Tatooine (Ubuntu. CC3D 4.2.5). 
Using 100K MCS (instead of 10K) in the project attached above.
`Processors   Time(sec)
  1                    677
  2                    664
  4                    407
  8                    239
16                    205`

Using two processor versus one gives no speedup, and increasing processors by 8X only increases the speed by 2.8X. Using 16 processors is basically the same as 8 processors.

In all cases Ubuntu reports the total CPU usage for the jobs as they are running as the expected value based on the requested number of processors. For example, when 16 processors are requested Ubuntu's "top" command reports 1600% CPU usage for the job.

**Comment by CompuCell3D** [comment]
Can you post the simulation you used for benchmarking?

**Comment by jpsluka** [comment]
It is linked in my first post [DynamicNumberOfProcessors.zip](https://github.com/CompuCell3D/CompuCell3D/files/8970768/DynamicNumberOfProcessors.zip)

**Comment by CompuCell3D** [comment]
Interestingly, it looks like DiffusionSolverFE in 2D does not benefit from PArallelization. It looks like a bug, (unless we did not parallelize this solver at all). Clearly this needs to be fixed. Potts Scales as expected 8 CPUs - 4 times faster I think this is what we have seen before (roughly)

**Comment by maciekswat** [comment]
Fixed
