### ISSUE TITLE
CC3D 4.3.1 installation problem (by Pedro)

### ISSUE THREAD

**Issue by pdalcastel** [CompuCell3D/CompuCell3D#570]
CC3D didn't install correctly.
Screenshot of the installation attempt:
![image](https://user-images.githubusercontent.com/105459764/182954598-5911abef-2b0a-416f-a509-720bc787efe5.png)

**Comment by pdalcastel** [comment]
Solved by TJ. He told me to run the commands once cc3d was installed (on cmd in the installation folder):

conda activate ./Miniconda3
conda install -c conda-forge graphviz=2.38.0
conda install -c conda-forge -c compucell3d compucell3d

**Comment by CompuCell3D** [comment]
I wonder if it would help to remove c:\CompuCell3D manually fully before running installer? I know you have to be administrator to remove some of the miniconda files from previous installation. This is what I typically to if I retry installer. 

I can work on installer too to make sure this step is done autimatically

**Comment by pdalcastel** [comment]
I will try installing it again and let you know

Em sáb., 1 de abr. de 2023 15:03, maciekswat ***@***.***>
escreveu:
