### ISSUE TITLE
Problem taking screenshots in player on Ubuntu

### ISSUE THREAD

**Issue by jpsluka** [CompuCell3D/CompuCell3D#572]
A user reports problems getting Player to take screenshots on Ubuntu. Clicking the camera icon crashes.  See the reddit at https://www.reddit.com/r/CompuCell3D/comments/wf99gz/compucell3d_player_crashing_if_screenshot_data_is/

**Comment by maciekswat** [comment]
This should be fixed in the new release. I checked and the screenshots look ok . No crash when pressing camera button
