### ISSUE TITLE
[Major] When changing cell types with different diffusion constant the diffusion constant is not updated

### ISSUE THREAD

**Issue by JulianoGianlupi** [CompuCell3D/CompuCell3D#575]
If the cell is frozen, when we change from a cell type with diffusion constant=0 to a cell type with D>0 the chemical does not diffuse through the D>0 cell. I've attached a simulation that exemplifies the problem

[debug_diffusion.zip](https://github.com/CompuCell3D/CompuCell3D/files/9304260/debug_diffusion.zip)

This bug happens because the D update happens only on successful pixel flips. This sim exemplifies that the diffusion only starts with pixels that have changed cell

[debug_diffusion_unfrozen.zip](https://github.com/CompuCell3D/CompuCell3D/files/9304277/debug_diffusion_unfrozen.zip)

**Comment by pdalcastel** [comment]
I will try:

1) Delete the cell
2) Build a new cell of a different type over the same pixels

And let you know

**Comment by maciekswat** [comment]
fixed. thanks @JulianoGianlupi  for reporting it
