### ISSUE TITLE
BUG: Problems with user fields (and perhaps all fields) if model is not square

### ISSUE THREAD

**Issue by jpsluka** [CompuCell3D/CompuCell3D#583]
If the dimensions of the model are not the same on X and Y and you have users fields, the field is only displayed on both axis to the length of the shorter axis.
Windows 10, CC3D 4.3.1 rev 0
Starting with the demo 
`C:\CompuCell3D\Demos\CompuCellPythonTutorial\pressureField\`
With dimensions
`         <Dimensions x="200" y="200" z="1"/>`
typical output is
![image](https://user-images.githubusercontent.com/22944062/189496167-d8a8def8-a55f-4959-9632-e8e88d9a2c46.png)

Change the dimensions so model is not square
`        <Dimensions x="200" y="150" z="1"/>`
typical output is
![image](https://user-images.githubusercontent.com/22944062/189496208-49ee3f79-5332-4e51-875b-cb68d2121781.png)

Note that the field is only shown for 150x150

A possible related problem is seen with the demo
`C:\CompuCell3D\Demos\CompuCellPythonTutorial\ExtraFields`
Changing the model dimensions so it isn't square crashes player when a field is displayed.
Deleting the _settings.sqlite file doesn't fix the problem.

**Comment by maciekswat** [comment]
This has been already fixed and the issue was a bug in C++ field extractors
