### ISSUE TITLE
Can't easily use ipython notebooks and can't easily add modules into the CC3D python's structure

### ISSUE THREAD

**Issue by jpsluka** [CompuCell3D/CompuCell3D#584]
The Python install for CC3D appears to have jupyter notebooks included. 
But it is very difficult, actually impossible to me, to add new modules into that python install that a jupyter notebook can use.

Adding modules with pip or pip3 says everything installed but the modules are not accessible in the notebooks.

Adding modules with 'conda install' does not appear to work either. Conda says everything is OK but the modules can't be imported into the jupyter notebooks.

The specific package I am trying to install are PIL (python image library) or IMAGE, and cv2 (opencv)

**Comment by tjsego** [comment]
Jupyter notebook is not currently part of the package dependencies, and I don't see it in the installation. @jpsluka where are you seeing notebook in the installed environment?

I could successfully import ``cc3d`` and ``cv2`` in a Jupyter notebook on Windows 10 with a system installation of conda using the following procedure:

- Create a new conda environment (*e.g.*, ``conda create -n cc3denv``)
- Activate the new conda environment (*e.g.*, ``conda activate cc3denv``)
- Issue the command ``conda install -y -c compucell3d -c conda-forge cc3d cc3d-player5 cc3d-twedit5 opencv notebook``
- Launch jupyter notebook from the activated environment (*e.g.*, ``jupyter notebook``)
- Import ``cc3d`` and ``cv2`` in a notebook

When targeting the environment installed by the installer, the following procedure also worked for me:

- Activate the installed environment (*e.g.*, ``conda activate %PATH_TO_INSTALL%\Miniconda3``)
- Issue the command ``conda install -y -c conda-forge opencv notebook``
- Launch jupyter notebook from the activated environment
- Import ``cc3d`` and ``cv2`` in a notebook

**Comment by jpsluka** [comment]
Hmm, those Jupyter files must have been from a failed attempt to install Jupyter.

**Comment by jpsluka** [comment]
Now how do I install regular old CC3D without having multiple python installations?

**Comment by tjsego** [comment]
> Now how do I install regular old CC3D without having multiple python installations?

You can use the installer as before, which will install its own python installation. Or you can install into any existing conda environment.

**Comment by maciekswat** [comment]
It is probably better to install via binary installer. this way you are not
messing up any conda installation, as TJ mentioned old installer
bundles python and installs everything in a separate folder so no conda
environment is afected

**Comment by maciekswat** [comment]
@tjsego @jpsluka can we close this issue now. Has it been resolved?

**Comment by tjsego** [comment]
> @tjsego @jpsluka can we close this issue now. Has it been resolved?

I think so. V4.4.0 release makes usage in Jupyter completely typical. While there are new docs on general usage, API docs would significantly improve usability. Maybe the installer could also include a shell script to launch a terminal with the installer-built environment activated. But generally, I think that this problem is solved for CC3D.

**Comment by maciekswat** [comment]
Closing it then!
