### ISSUE TITLE
Bug in cell-level field visualization in 3D

### ISSUE THREAD

**Issue by CompuCell3D** [CompuCell3D/CompuCell3D#587]
2D view looks as follows:
<img width="377" alt="image" src="https://user-images.githubusercontent.com/5247233/191393759-e6ae4443-2a6e-4614-85f3-97e2d5de23f0.png">
while 3D looks buggy:
<img width="388" alt="image" src="https://user-images.githubusercontent.com/5247233/191393819-03558872-f582-4b4e-a169-9d43134a55ac.png">

**Comment by jpsluka** [comment]
I think part of the problem may be that the field values is being interpreted as a cell type and that causes the missing cells (any cell with a field value near zero is assumed to be medium).

The coloring error might be a derivative of that misinterpretation of the cell level field as a cell type ID.

**Comment by jpsluka** [comment]
see also 
 scalar_field_cell_level don't render in 3D #15 
in [cc3d-player5](https://github.com/CompuCell3D/cc3d-player5)
https://github.com/CompuCell3D/cc3d-player5/issues/15

**Comment by CompuCell3D** [comment]
OK, I will need to recode this part of the visualization pipeline. I have a working prototype and will update 3D concentration rendering soon so stay tuned

**Comment by CompuCell3D** [comment]
After fixes the field will look as follows:
<img width="395" alt="image" src="https://user-images.githubusercontent.com/5247233/198854544-900461e7-aca9-4a8b-a1d6-c6ebff2eecc0.png">

**Comment by CompuCell3D** [comment]
There are sill artifacts from marching cubes algorithm but for now it is a better solution that current visualization method

**Comment by maciekswat** [comment]
Fixed. Closing it
