### ISSUE TITLE
Simulation runs slower if you run simulation multiple times on same player instance

### ISSUE THREAD

**Issue by anwarsk** [CompuCell3D/CompuCell3D#59]
Simulation in CompuCell3D runs slower when you run it same player instance again and again.  if you are editing the python scripts in Twedit++. If you run simulation it will run faster at first instance than future runs.

I have experience this issue on Ubuntu as well as Mac machine. I suspect there must be some memory leak or uncleared resource allocation.

**Comment by tjsego** [comment]
Resolved by #423. Closing.
