### ISSUE TITLE
Windows, v4.3.1: crash to desktop when visualizing fields and pausing

### ISSUE THREAD

**Issue by JulianoGianlupi** [CompuCell3D/CompuCell3D#596]
If the cell window is set to a field and pause is hit CC3D crashes to desktop (terminal also crashes). This happened on an installation that used the installer, I just tested on a pure conda install and it seemed to work

**Comment by CompuCell3D** [comment]
Can you provide a minimal simulation that shows this error?

**Comment by jpsluka** [comment]
This might also be related to #583 and maybe #587

**Comment by maciekswat** [comment]
This should be fixed in 4.3.2

**Comment by maciekswat** [comment]
Fixed
