### ISSUE TITLE
Windows, v4.3.1: When opening a symulation from twedit no cmd window is created, and no output to cmd is given

### ISSUE THREAD

**Issue by JulianoGianlupi** [CompuCell3D/CompuCell3D#597]
Twedit doesn't open a terminal anymore, this means that when a simulation is launched from twedit there's no print output and there's no way to check error messages

**Comment by jpsluka** [comment]
On my windows install of 4.3.1, the Player output is written to the same command window as the twedit++ output.

**Comment by maciekswat** [comment]
Seems to be fine. Closing it for now - we may reopen if indeed this issue persists
