### ISSUE TITLE
Player crashed with invalid state loads the settings on next instance 

### ISSUE THREAD

**Issue by anwarsk** [CompuCell3D/CompuCell3D#62]
During workshop we had a weird issue with on one of the participant's computer. She tried running parameter scan and her player crashed. Afterward she is able to open the CC3D player. Though she opens another project from demo folder, as soon as she click on the Run button CompuCell Crashes with following message-

```
Qt has caught an exception thrown from an event handler. Throwing
exceptions from an event handler is not supported in Qt. You must
reimplement QApplication::notify() and catch all exceptions there.

libc++abi.dylib: terminating with uncaught foreign exception
/Users/nat/Downloads/CC3D_3.7.5/compucell3d.command: line 155:   850 Abort trap: 6           ${PYTHON_EXEC} ${PREFIX_CC3D}/player/compucell3d.pyw $* --currentDir=${PREFIX_CC3D}
logout
```

I tried-
1. Removing and reinstalling CompuCell3D on her machine same as well as different directory than earlier
2. Installing different versions as 3.7.5 and 3.7.6 both 
3. Removing the directory which used as a workspace for CompuCell3D
4. Restarting the machine

Nothing seems to fix the issue.  Machine was MacBook Pro 13 running OS X El Capitan version 10.11

**Comment by anwarsk** [comment]
**Workaround:**

Removing <home dir>/.compucell3d/_settings.xml and possibly _settings.xml from the directory of the project you are trying to run. This could be a possible workarouond.

**Comment by maciekswat** [comment]
closing. We switched away from saving settings as XML file
