### ISSUE TITLE
it is likely that the random seed might not work properly starting with 4.3.0, , 4.3.1

### ISSUE THREAD

**Issue by maciekswat** [CompuCell3D/CompuCell3D#628]

**Comment by maciekswat** [comment]
Fixed, in the meantime the workaround is to use legacy RNG - the relevant pies of `Potts` section should look like this
```xml
    <Potts>
        ...
        <RandomNumberGenerator Name="Legacy"/>
        <RandomSeed>2</RandomSeed>
        ...
    </Potts>
```

**Comment by jpsluka** [comment]
The "legacy" tag doesn't seem to work.

**Comment by jpsluka** [comment]
Yes, that looks like it works. So, you need both the legacy and then to explicitly set a seed.

        <RandomNumberGenerator Name="Legacy"/>
        <RandomSeed>3697</RandomSeed>

User needs to edit the project’s xml for each run, or perhaps do a pscan with the seed as the target of the scan.

I also tried just randomly reassigning cell types in a steppable after the initial layout was generated by the blobinitalizer, which also works and is automatic.

Jim

James P. Sluka, PhD
Biocomplexity Institute
Intelligent Systems Engineering
School of Informatics, Computing and Engineering
Indiana University
Bloomington, IN   USA
Office: 812-855-2441
Cell: 317-331-7465

**Comment by maciekswat** [comment]
Fixed
