### ISSUE TITLE
CC3D on Mac: Opening the software does not load the UI elements completely

### ISSUE THREAD

**Issue by anwarsk** [CompuCell3D/CompuCell3D#63]
When you open CompuCell3D on Mac most of the UI buttons on the toolbar are not visible. If you hover over then they start appearing. It takes a while until they become clickable and functional.

**Comment by maciekswat** [comment]
This is a know issue with PyQt5. Any PyQt5 Application on OSX behaves like that. A temporary workaround is to bring forward other application and then switch back to CC3D.

**Comment by tjsego** [comment]
Resolved as not a CC3D issue. Closing.
