### ISSUE TITLE
Twedit++Save Errors can erase file contents

### ISSUE THREAD

**Issue by j00095289754** [CompuCell3D/CompuCell3D#64]
Hitting "save" or "saveAll" in Twedit++ can destroy the contents a file irrecoverably if the save generates an error. In this case, the current file is replaced by an empty file. If the file were deleted outright, the contents would be recoverable from the Recycle or trash folder. However, an overwrite is immediate and irrecoverable. Ideally, Twedit++ should save a previous state of all files which would allow rollback or recovery after a crash like this.

**Comment by anwarsk** [comment]
Fixed Issue in pull request #71 

Created a backup directory with name .backup. Which will hold a copy of the file before saving. Incase of exception that copy will be retrieved and replaced with original file.

Commit: 4e3bb5d6ab9715be81c7dc7f4e0e7e23b48a5162
