### ISSUE TITLE
Shapes with initial conditions

### ISSUE THREAD

**Issue by maciekswat** [CompuCell3D/CompuCell3D#649]
Python API

**Comment by jpsluka** [comment]
I have Python code that will return a set of lattice positions inside an arbitrary polygon defined by a set of vertexes. It could be modified to "know" basic shapes (circle, square, rectangle, triangle, hexagon, ...) and still be able to handle arbitrary vertex lists.
Currently only in 2D but easy enough to extrude to 3D. Actual 3D list of vertex should be do-able.

**Comment by maciekswat** [comment]
Send it to me Jim and I can include it. Unless you want to write PR yourself (I can help you with the gitt setup)

**Comment by maciekswat** [comment]
@fyffep let's add hexagon initializer
