### ISSUE TITLE
Improve Documentation on Parameter Scans

### ISSUE THREAD

**Issue by j00095289754** [CompuCell3D/CompuCell3D#65]
I think we should add to the parameter scan documentation how you could use the scan infrastructure to do multiple runs with the same set of parameters for cases where you need multiple runs to address run-to-run variability. If you add a dummy global variable to the python script you can scan that value. Since the variable isn’t actually used anywhere the resulting runs would all use the same parameter set.

**Comment by maciekswat** [comment]
added and fixed
