### ISSUE TITLE
Is CellDraw no longer supported?

### ISSUE THREAD

**Issue by Xemin0** [CompuCell3D/CompuCell3D#658]
Trying to convert some image files to PIF for cell initializations, I went through the manual on the official site where it is suggested to use `CellDraw` from branch 3.7.9 from this repo, which requires `pyqt4`. 
But `pyqt4` is not available anywhere now ( I tried to install it under virtual env with python=3.5)
Any suggestions or workarounds?

**Comment by jpsluka** [comment]
CellDraw is pretty old and is no longer supported.

If the layout of cells is not to complex you can jut manually created the cells in CC3D. For more complex layouts you can read agif or jpg version of the layout into CC3D and iterate over all the pixels to create your cell layout. This can get tricky but can be done. Here are two pages with some help:

1. https://compucell3d.org/QuickModels/ImportImageSimple
2. https://compucell3d.org/QuickModels/ImportImage2Cells

If you need help, or just want an opinion on a good approach, you can email a screen shot to jsluka@iu.edu
