### ISSUE TITLE
iteration 2 on the polygon initializer and tube initializer

### ISSUE THREAD

**Issue by CompuCell3D** [CompuCell3D/CompuCell3D#677]
let's address comments from the original PRs

https://github.com/CompuCell3D/CompuCell3D/pull/666
https://github.com/CompuCell3D/CompuCell3D/pull/674

This would likely require developing classes that can be reused in tube initializer and other cc3d modules

**Comment by CompuCell3D** [comment]
let's also add some examples  to Demos/steppables to show how to use those new modules

**Comment by fyffep** [comment]
I added the ability to create wedge cells. Examples:
![perfect8Tube](https://github.com/CompuCell3D/CompuCell3D/assets/79017811/a5b98cf4-3327-4d82-8473-06ebbbc4088a)
You can choose the number of slices in XML. By default, it's 8. Here is 16:
![16slices](https://github.com/CompuCell3D/CompuCell3D/assets/79017811/1e53a45e-f89c-4091-b8a7-f491ca95977b)
You can also mix and match the cell shape:
![mixMatch](https://github.com/CompuCell3D/CompuCell3D/assets/79017811/40210510-bb75-4659-beb9-be03fcc4842e)
![variedWedges](https://github.com/CompuCell3D/CompuCell3D/assets/79017811/f0014664-0460-474c-a3ac-3ea59cc65c51)

The ends of the tubes are not always perfect, but I feel that what I have now is fine.
![crinkleCut](https://github.com/CompuCell3D/CompuCell3D/assets/79017811/2b771213-acbd-473d-b423-92871a4f41d3)
Finally, here is how my code handles a tube that's too large for the bounding box:
![tubeTooLarge](https://github.com/CompuCell3D/CompuCell3D/assets/79017811/002b95f0-3cac-4ec5-ae6e-6c0daf578b44)

Example XML
```
<Steppable Type="TubeInitializer">
      <Region>
          <InnerRadius>8</InnerRadius>
          <OuterRadius>11</OuterRadius>
         <Gap>0</Gap>
         <Width>2</Width>
         <Types>Condensing</Types>
         <Extrude>
           <From x="15" y="45" z="25" />
           <To x="15" y="10" z="25" />
         </Extrude>
        <CellShape>Wedge</CellShape>
        <NumSlices>1</NumSlices>
      </Region>
      <Region>
          <InnerRadius>0</InnerRadius>
          <OuterRadius>7</OuterRadius>
         <Gap>0</Gap>
         <Width>2</Width>
         <Types>NonCondensing</Types>
         <Extrude>
           <From x="15" y="45" z="25" />
           <To x="15" y="10" z="25" />
         </Extrude>
        <CellShape>Cube</CellShape>
        <NumSlices>8</NumSlices>
      </Region>
   </Steppable>
```

**Comment by fyffep** [comment]
Note to self: 'Gap' remains broken for the tubes with wedge cells.

**Comment by fyffep** [comment]
There is also a small bug where tubes extruded along the y-axis may be missing some cells near their ends:
![image](https://github.com/CompuCell3D/CompuCell3D/assets/79017811/5014cf0c-bdd8-47fb-a848-e95b33dcbc01)

**Comment by jpsluka** [comment]
This looking really good. As someone pointed out, a demo showing usage would be great. If you can generate an image, or multiple images, I can highlight the capability on the CC3D web site on the visual examples page https://compucell3d.org/QuickModels.

If you do demos, it could be one big demo, or individual demos for the various structures, which could all be put in the same sub-folder of Demos.
