### ISSUE TITLE
'sim is null' when attempting to modify Player Configuration

### ISSUE THREAD

**Issue by fyffep** [CompuCell3D/CompuCell3D#680]
When opening Player, attempting to change any Configuration settings will cause a crash unless a simulation is running. Some settings, such as the movie and screen shot managers, should allow editing even without a simulation loaded in. 
This may also resolve the issue #627

**Comment by jpsluka** [comment]
Tried to reproduce this behavior but it is hard to not actually have a sim in Player (v 4.4.1). Player seems to automatically load the last sim run. 

Windows 11, CC3D 4.4.1, launch Player. Edit params is OK. Click run and a simulation runs, even though one was never loaded.

Delete the system _settings.sqlite (e.g., C:\Users\jsluka\.compucell3d_py3). Launch Player. Run does nothing but the parameters in Player are editable without a crash.

**Comment by fyffep** [comment]
My apologies. This was just an issue with my machine. It seemed like it had been happening for a long time, but it must have arisen from one of my code changes. I took some time to reset my Conda env so that it would reflect the master branch of CompuCell core and Player5. I also deleted the settings file as suggested. That resolved it.
