### ISSUE TITLE
Can't automatically save multiple 3D videos with player in 4.5.0

### ISSUE THREAD

**Issue by tc2fh** [CompuCell3D/CompuCell3D#723]
When I click the camera button on a second 3D player window (viewing from different angles), I get a popup message saying that settings are already saved for this view and it asks me if I'd like to overwrite these settings. I am unable to have player save screenshots for multiple 3D views and save them as mp4 videos after a player run.

**Comment by maciekswat** [comment]
Yes, this is unsupported currently. You might be able to hack screenshot description json as a workaround

**Comment by maciekswat** [comment]
this should be fixed now

**Comment by maciekswat** [comment]
Closing it
