### ISSUE TITLE
The MCS displayed in movies is incorrect.

### ISSUE THREAD

**Issue by jpsluka** [CompuCell3D/CompuCell3D#739]
The MCS displayed in movies created by Player is incorrect. The attached simulation does 7,000 MCS and all frames are in the movie, but the MCS displayed in the movie only goes up to 1100 instead of 7000.
[Gilberto_venturi_movie_mcs_bug.zip](https://github.com/user-attachments/files/16419467/Gilberto_venturi_movie_mcs_bug.zip)

**Comment by fyffep** [comment]
I reproduced this, and it is indeed a bug.

**Comment by fyffep** [comment]
It should be fixed now. It was a really small change: 1589c2f
