### ISSUE TITLE
Python Functionality and Player: Expose selected Python Parameters to Steering

### ISSUE THREAD

**Issue by j00095289754** [CompuCell3D/CompuCell3D#78]
At the moment, the Player Steering window only allows changes in parameters specified through CC3DML. Would it be possible to add a Python class, named something like "expose_Python_parameter_to_steering" which allowed a user-defined Python parameter to show up in the Steering widow tree and be manipulated in the same way that current CC3DML parameters are?

**Comment by tjsego** [comment]
Steering supports modifying parameters defined in Python. Closing.
