### ISSUE TITLE
How to compile CompuCell3D from CLI?

### ISSUE THREAD

**Issue by lmiroslaw** [CompuCell3D/CompuCell3D#8]
I am trying to compile cc3d on a virtual machine with no access to GUI, therefore I cannot run cmake-gui.

Could you shortly explain how to compile the project from CLI using plain old cmake?

Thank you,
Lukasz

**Comment by maciekswat** [comment]
If you are on windows - take a look at this python script which I use to build CC3D release binaries - it relies on CLI tools only - no GUI's
https://github.com/CompuCell3D/cc3d_build_scripts/blob/master/windows/373/win_cc3d_builder_373.py

CLI workflow for linux builds can be found here - again no gui's
https://github.com/CompuCell3D/cc3d_build_scripts/blob/master/linux/373/build-debian-cc3d-373.sh

Let me know if this helps
