### ISSUE TITLE
Generating PIF file

### ISSUE THREAD

**Issue by priyomadhyapok** [CompuCell3D/CompuCell3D#87]
On hitting the 'Run' button for a simulation, the player option under Tools-> Generate PIF file from current snapshot doesn't work.Don't seem to have much luck with writing the code for a PIFDumper Steppable either. But hitting 'Step' once and then pausing or running the code afterwards lets you generate a PIF file from the player.

**Comment by maciekswat** [comment]
Fixed it. Will go live in the upcoming release
