### ISSUE TITLE
BoundaryPixelTracker prints line "neighborOrder" to screen

### ISSUE THREAD

**Issue by priyomadhyapok** [CompuCell3D/CompuCell3D#93]
Using the BoundaryPixelTracker keeps printing "_neighborOrder=value" to the screen . I checked and the print keeps to be independent of how the DebugOutputFrequency might be called.

**Comment by CompuCell3D** [comment]
It looks like this has been already fixed  in the "master branch". Could you post the xml code for you simulation for which you get the printout? Also what version of CC3D are you using? Have you compiled cc3d or used pre-compiled binaries (if so which version)?

**Comment by priyomadhyapok** [comment]
I am still using version 3.7.5 (CompuCell3DElmnt=ElementCC3D("CompuCell3D",{"Revision":"20160527","Version":"3.7.5"}) and had compiled cc3d.

Calling the relevant XML plugin as  
bptp = CompuCell3DElmnt.ElementCC3D("Plugin",{"Name":"BoundaryPixelTracker"})

**Comment by CompuCell3D** [comment]
I think if you compile the latest snapshot of branch master this error will disappear. Try it and let me know if the problem got solved
