### ISSUE TITLE
install earlier cc3d version

### ISSUE THREAD

**Issue by nadaa** [CompuCell3D/CompuCell3D#97]
Hi,
I want to install cc3d 3.7.5 under ubuntu. I used the  steps:
http://www.compucell3d.org/SrcBin/LinuxCompile

but the last version was installed?

Thanks

**Comment by nadaa** [comment]
Thank you maciekswat.
This should be after the clone right?

**Comment by maciekswat** [comment]
yes

**Comment by nadaa** [comment]
Thanks.
I installed cc3d 3.7.5 but got this error "this example requires a numerical python extension, but failed to import either NumPy or numarray...." 

although I have numpy installed and I can import it?

**Comment by maciekswat** [comment]
What platform are you on? Ubuntu? If so which version?

**Comment by nadaa** [comment]
Thanks maciekswat, I could install version 3.7.5.
I remembered that I encountered the same problem with Numpy, and you helped me to solve it!.

**Comment by CompuCell3D** [comment]
Closing it for now. Please reopen if necessary but we are already on 4.x branch
