### ISSUE TITLE
AdhesionFlexPython demo seems to behave in an unexpected manner 

### ISSUE THREAD

**Issue by jingjieyeo** [CompuCell3D/CompuCell3D#98]
Dear admins, I tried running the AdhesionFlexPython demo on both CC3D 3.7.7 and 3.7.6 in Mac OSX High Sierra and I encountered a strange problem where the moment the adhesions are changed by the AdhesionFlexSteppables.py script, the VTK outputs all zeroes for all entries (such as CellID, CellType, ClusterID).

I have a video on the forum showing an unmodified run of the demo where all the cells slowly disappeared, it appears that their cell types are being gradually changed to zero. 
[Link](https://www.allanswered.com/post/eqpqp/vtk-output-problem-when-running-adhesionflexpython/)

May I know whether this is a bug or I have not correctly understood what adhesionflex is doing?

**Comment by maciekswat** [comment]
Please post any simulation-related problems on https://www.allanswered.com/community/s/compucell3d/

There are many people there who can help you with your problem. Github is only for  core-software development issues
