### ISSUE TITLE
Disappearing cells

### ISSUE THREAD

**Issue by paulitikka** [CompuCell3D/CompuCell3D#99]
Dear developer,

I loose the record of a some cells at the end of my simulation, what could be the cause for it?

An example file extraction:

cell_no,time_mcs,x_position_(px),y_position_(px)
...
428,966,22.6896551724,14.8965517241
429,966,22.56,36.12
428,967,22.6153846154,15.1923076923
429,967,22.7083333333,35.9166666667
428,968,22.7037037037,14.851851

STOPS??

There should be 999 entries?

Best regards,
Pauli

**Comment by paulitikka** [comment]
Especially when I change the chemo-taxis lambda, this happens. Is there something wrong with my model, or the code?

**Comment by maciekswat** [comment]
Please post any simulation-related problems on https://www.allanswered.com/community/s/compucell3d/

There are many people there who can help you with your problem. Github is only for core-software development issues
